---
sidebar: sidebar 
permalink: express/express-direct-attach-design_technology_requirements.html 
keywords: requirements, hardware, software, A220, HA, VIC, B200 m5, fabric interconnect, VMware, vCenter, Server, Appliance, ESXi, hypervisor 
summary: FlexPod Express システムには、ハードウェアコンポーネントとソフトウェアコンポーネントを組み合わせて使用する必要があります。FlexPod Express では、システムにハイパーバイザーノードを追加するために必要なハードウェアコンポーネントについても、 2 つのユニット単位で説明します。 
---
= テクノロジ要件
:allow-uri-read: 


[role="lead"]
FlexPod Express システムには、ハードウェアコンポーネントとソフトウェアコンポーネントを組み合わせて使用する必要があります。FlexPod Express では、システムにハイパーバイザーノードを追加するために必要なハードウェアコンポーネントについても、 2 つのユニット単位で説明します。



== ハードウェア要件

選択したハイパーバイザーに関係なく、すべての FlexPod Express 構成で同じハードウェアが使用されます。そのため、ビジネス要件が変わっても、どちらのハイパーバイザーも同じ FlexPod Express ハードウェア上で実行できます。

次の表に、すべての FlexPod 構成に必要なハードウェアコンポーネントを示します。

[cols="50,50"]
|===
| ハードウェア | 数量 


| AFF A220 HA ペア | 1. 


| Cisco UCS B200 M5 サーバ | 2. 


| Cisco Nexus 31108PCV スイッチ | 2. 


| B200 M5 サーバの Cisco UCS Virtual Interface Card （ VIC ；仮想インターフェイスカード） 1440 | 2. 


| 2 つの統合 UCS-fi-M6324 ファブリックインターコネクトを備えた Cisco UCS Mini | 1. 
|===


== ソフトウェア要件

次の表に、 FlexPod Express ソリューションのアーキテクチャを実装するために必要なソフトウェアコンポーネントを示します。

[cols="33,33,33"]
|===
| ソフトウェア | バージョン | 詳細 


| Cisco UCS Manager の略 | 4.0 （ 1b ） | Cisco UCS ファブリックインターコネクト FI-6324UP の場合 


| Cisco Blade ソフトウェア | 4.0 （ 1b ） | Cisco UCS B200 M5 サーバの場合 


| Cisco nenic ドライバ | 1.0.25.0 | Cisco VIC 1440 インターフェイスカードの場合 


| Cisco NX-OS | 7.0 （ 3 ） I6 （ 1 ） | Cisco Nexus 31108PCV スイッチの場合 


| NetApp ONTAP | 9.5 | AFF A220 コントローラの場合 
|===
次の表に、 FlexPod Express のすべての VMware vSphere 環境に必要なソフトウェアを示します。

[cols="50,50"]
|===
| ソフトウェア | バージョン 


| VMware vCenter Server Appliance の略 | 6.7U1 


| VMware vSphere ESXi ハイパーバイザー | 6.7U1 
|===
link:express-direct-attach-design_design_choices.html["次のステップ：設計の選択肢。"]
