---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_deployment_procedures_overview.html 
keywords: configure,  express, flexpod, cisco, series, c190, deployment, overview 
summary: このドキュメントでは、完全な冗長性と高可用性を備えた FlexPod Express システムの構成について詳しく説明します。この冗長性を反映するために、各手順で設定するコンポーネントをコンポーネント A またはコンポーネント B と呼びます 
---
= 概要
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


このドキュメントでは、完全な冗長性と高可用性を備えた FlexPod Express システムの構成について詳しく説明します。この冗長性を反映するために、各手順で設定するコンポーネントをコンポーネント A またはコンポーネント B と呼びますたとえば、このドキュメントでプロビジョニングされている 2 台のネットアップストレージコントローラは、コントローラ A とコントローラ B で識別されます。スイッチ A とスイッチ B は Cisco Nexus スイッチのペアを表します。

また、このドキュメントでは、複数の Cisco UCS ホストをプロビジョニングする手順についても説明します。これらのホストは、サーバ A 、サーバ B などとして順次識別されます。

環境に関連する情報をステップに含める必要があることを示すために、コマンド構造の一部として「 \ <text>> 」が表示されます。「 vlan create 」コマンドについては、次の例を参照してください。

....
Controller01> network port vlan create –node <<var_nodeA>> -vlan-name <<var_vlan-name>>
....
本ドキュメントでは、 FlexPod Express 環境を完全に構成する方法について説明します。このプロセスでは、さまざまな手順で、お客様固有の命名規則、 IP アドレス、および VLAN （仮想 LAN ）スキームを入力する必要があります。次の表に、このガイドで説明するように、導入に必要な VLAN を示します。このテーブルは、特定のサイト変数に基づいて作成し、ドキュメントの設定手順を実装するために使用できます。


NOTE: 別々のインバンド管理 VLAN とアウトオブバンド管理 VLAN を使用する場合は、それらの間にレイヤ 3 ルートを作成する必要があります。この検証では、共通の管理 VLAN を使用しました。

|===
| VLAN 名 | VLAN の目的 | VLAN ID |  


| 管理 VLAN | 管理インターフェイス用の VLAN | 3437 | vSwitch0 


| NFS VLAN | NFS トラフィック用の VLAN | 3438 | vSwitch0 


| VMware vMotion VLAN | ある物理ホストから別の物理ホストへの仮想マシン（ VM ）の移動用に指定された VLAN | 3441 | vSwitch0 


| VM トラフィック VLAN | VM アプリケーショントラフィック用の VLAN | 3442 | vSwitch0 


| iSCSI-A VLAN | ファブリック A の iSCSI トラフィック用 VLAN | 3439 | iScsiBootvSwitch 


| iSCSI-B VLAN | ファブリック B の iSCSI トラフィック用 VLAN | 3440 | iScsiBootvSwitch 


| ネイティブ VLAN | タグなしフレームが割り当てられている VLAN | 2. |  
|===
VLAN 番号は、 FlexPod Express の設定全体で必要になります。VLAN は「 \<<var_xxxx_vlan>> 」と呼ばれます。「 xxxx 」は VLAN の目的（ iSCSI-A など）です。

この検証で作成される vSwitch は 2 つです。

次の表に、解決策 vSwitch を示します。

|===
| vSwitch の名前 | アクティブなアダプタ | ポート | MTU | 負荷分散 


| vSwitch0 | vmnic2 、 vmnic4 | デフォルト（ 120 ） | 9 、 000 | IP ハッシュに基づいたルート 


| iScsiBootvSwitch | vmnic3 、 vmnic5 | デフォルト（ 120 ） | 9 、 000 | 発信元の仮想ポート ID に基づいたルート。 
|===

NOTE: ロードバランシングの IP ハッシュ方式では、スタティック（モードオン）ポートチャネルで SRC-DST-IP EtherChannel を使用する基盤となる物理スイッチを適切に設定する必要があります。スイッチの設定ミスにより接続が断続的に中断される場合は、ポートチャネル設定のトラブルシューティングを行う間、 Cisco スイッチ上の 2 つの関連するアップリンクポートのいずれかを一時的にシャットダウンして ESXi 管理 vmkernel ポートへの通信をリストアします。

次の表に、作成される VMware VM を示します。

|===
| VM 概要の略 | ホスト名 


| VMware vCenter Server の各機能を使用し | FlexPod - VCSA 


| Virtual Storage Console の略 | Flexpo-VSC 
|===