---
sidebar: sidebar 
permalink: express/express-direct-attach-aff220-deploy_program_summary.html 
keywords: flexpod, express, vmware, vsphere, aff, direct, attached, ip, based, storage 
summary: FlexPod Express は、 Cisco Unified Computing System （ Cisco UCS ）、 Cisco Nexus ファミリースイッチ、およびネットアップストレージテクノロジを基盤とした、事前設計されたベストプラクティスアーキテクチャです。FlexPod Datacenter と FlexPod Express は、仮想化、ベアメタル OS 、エンタープライズワークロードに最適なプラットフォームです。 
---
= NVA-1131 - 導入： VMware vSphere 6.7U1 搭載の FlexPod Express と、直接接続型の IP ベースのストレージを搭載した NetApp AFF A220
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ネットアップ、 Sree Lakshmi Lanka です

業界のトレンドは、共有インフラとクラウドコンピューティングへの大規模なデータセンターの移行を示しています。さらに、リモートオフィスやブランチオフィスにもシンプルで効果的な解決策を導入し、データセンターでよく使用されているテクノロジを活用することができます。

FlexPod Express は、 Cisco Unified Computing System （ Cisco UCS ）、 Cisco Nexus ファミリースイッチ、およびネットアップストレージテクノロジを基盤とした、事前設計されたベストプラクティスアーキテクチャです。FlexPod Express システムのコンポーネントは、 FlexPod Datacenter と同様に、小規模な IT インフラ環境全体での管理面の相乗効果を実現します。FlexPod Datacenter と FlexPod Express は、仮想化、ベアメタル OS 、エンタープライズワークロードに最適なプラットフォームです。

FlexPod Datacenter と FlexPod Express は、ベースライン構成が可能で、多種多様なユースケースや要件に対応できるよう、サイジングと最適化が可能な汎用性を備えています。FlexPod データセンターを利用している既存のお客様は、使い慣れたツールを使用して FlexPod Express システムを管理できます。FlexPod Express の新規のお客様は、環境の拡大に合わせて FlexPod データセンターの管理を容易に行うことができます。

FlexPod Express は、リモートオフィスやブランチオフィス（ ROBO ）、中堅企業向けの最適なインフラ基盤です。また、専用のワークロードにインフラを提供したいお客様にも最適な解決策です。

FlexPod Express は、ほぼすべてのワークロードに適した、管理しやすいインフラを提供します。
