---
sidebar: sidebar 
permalink: express/express-c-series-c190-design_technology_requirements.html 
keywords: software, hardware, hypervisor, network, AFF C190, Cisco UCS C220 M5, Cisco VIC 1457, VMware vSphere ESXi, VAAI 
summary: FlexPod Express では、選択したハイパーバイザーとネットワークの速度に応じて、ハードウェアコンポーネントとソフトウェアコンポーネントを組み合わせる必要があります。また FlexPod 、ハイパーバイザーノードをシステムに追加するために必要なハードウェアコンポーネントが 2 つのユニットに配置されます。 
---
= テクノロジ要件
:allow-uri-read: 


[role="lead"]
FlexPod Express では、選択したハイパーバイザーとネットワークの速度に応じて、ハードウェアコンポーネントとソフトウェアコンポーネントを組み合わせる必要があります。また FlexPod 、ハイパーバイザーノードをシステムに追加するために必要なハードウェアコンポーネントが 2 つのユニットに配置されます。



== ハードウェア要件

選択したハイパーバイザーに関係なく、すべての FlexPod Express 構成で同じハードウェアが使用されます。したがって、ビジネス要件が変わっても、同じ FlexPod Express ハードウェア上で別のハイパーバイザーを使用できます。

次の表に、この FlexPod 構成に必要なハードウェアコンポーネントと、この解決策の実装に必要なハードウェアコンポーネントを示します。解決策の実装で使用されるハードウェアコンポーネントは、お客様の要件に応じて異なる場合があります。

[cols="50,50"]
|===
| ハードウェア | 数量 


| AFF C190 は 2 ノードクラスタです | 1. 


| Cisco UCS C220 M5 サーバ | 2. 


| Cisco Nexus 31108 スイッチ | 2. 


| Cisco UCS C220 M5 ラックサーバ用 Cisco UCS Virtual Interface Card （ VIC ；仮想インターフェイスカード） 1457 | 2. 
|===


== ソフトウェア要件

次の表に、 FlexPod Express 解決策のアーキテクチャを実装するために必要なソフトウェアコンポーネントを示します。

[cols="33,33,33"]
|===
| ソフトウェア | バージョン | 詳細 


| Cisco Integrated Management Controller （ CIMC ） | 4.0.4 | C220 M5 ラックサーバ用 


| Cisco NX-OS | 7.0 （ 3 ） I7 （ 6 ） | Cisco Nexus 31108 スイッチの場合 


| NetApp ONTAP | 9.6 | NetApp AFF C190 コントローラの場合 
|===
次の表に、 FlexPod Express のすべての VMware vSphere 環境に必要なソフトウェアを示します。

[cols="50,50"]
|===
| ソフトウェア | バージョン 


| VMware vCenter Server Appliance の略 | 6.7U2 


| VMware vSphere ESXi の場合 | 6.7U2 


| NetApp VAAI Plug-in for ESXi | 1.1.2 


| NetApp Virtual Storage Console の略 | 9.6 
|===
link:express-c-series-c190-design_design_choices.html["次のステップ：設計の選択肢。"]
