---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, datacenter, netapp, cisco, ucs, disk shelves 
summary: このセクションでは、FlexPod データセンター設計の電力要件とディスク シェルフのケーブル配線ガイドラインについて説明します。 
---
= 電源およびケーブル配線に関するガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、FlexPod データセンター設計の電源要件とケーブル配線ガイドラインについて説明します。



[[power-requirements]]
== 電力要件

FlexPod データセンターの電力要件は、 FlexPod データセンター構成のインストール場所によって異なります。

必要な最大電力およびその他の詳細な電力情報の詳細については、に記載されている各ハードウェアコンポーネントの技術仕様を参照してください link:dc-tech-spec_technical_specifications_and_references.html["技術仕様と参考資料：ハードウェアコンポーネント"]。

Cisco UCS の詳細な電力データについては、 https://ucspowercalculator.cisco.com/["Cisco UCS Power Calculator"^]を参照してください。

NetAppストレージコントローラの電源データについては、 https://hwu.netapp.com/["NetApp Hardware Universe の略"^]を参照してください。*プラットフォーム*で、使用するストレージプラットフォーム（例：AFF A90）を選択し、ONTAPバージョンを選択して、*結果を表示*をクリックします。電源コードのデータは、*対応電源コード*セクションに記載されています。サイズ、重量、ワット数などの詳細については、*サイズ、重量、音響特性、出力*セクションを参照してください。



[[cabling-guidelines]]
== ケーブル配線ガイドライン

このセクションでは、FlexPod データセンター設計の一般的なケーブル配線ガイドラインを説明します。

* コンピューティングおよびストレージ接続において、冗長な接続性を確保してください。
* 接続速度は、接続される機器の速度と互換性がある必要があります。
* 特定のトポロジーに関する追加のケーブル配線ガイドラインについては、link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["FlexPod データセンターのトポロジー"^]セクションを参照してください。


次の表に、NetApp ディスク シェルフのケーブル配線ガイドラインを示します。このディスク シェルフは、FlexPod データセンターの設計で使用できます。

|===


| ディスクシェルフ | ケーブル配線ガイドライン 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["SASケーブル配線規則"^] 


| DS224C 


| DS460C 


| NS224 .3+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["NS224およびNX224シェルフの要件とベストプラクティス"^] 


| NS224 w/NSM100B 


| NX224を使用したチャンク アップロード署名要求がサポートされるようになりました。 
|===