---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, switches, fabric, interconnects, servers, storage, controllers 
summary: FlexPod データセンター構成には、スイッチ、ファブリックインターコネクト、サーバ、ネットアップストレージコントローラなど、最小限のハードウェア要件が含まれますが、これらに限定されません。 
---
= ハードウェアの最小要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
FlexPod データセンター構成には、スイッチ、ファブリックインターコネクト、サーバ、ネットアップストレージコントローラなど、最小限のハードウェア要件が含まれますが、これらに限定されません。

FlexPod 構成には、ハードウェアに関する次の最小要件があります。

* 冗長構成の2台のCisco Nexusスイッチ。この構成は、前述のCisco Nexus 9000シリーズから2台の冗長スイッチで構成できます。2つのスイッチは同じモデルで、同じ動作モードで設定されている必要があります。



NOTE: ACIアーキテクチャをデプロイする場合は、次の追加要件を遵守する必要があります。* リーフスパイン型トポロジーを採用した Cisco Nexus 9000 シリーズスイッチをデプロイしてください。* 3つの Cisco Application Policy Infrastructure Controllers （APICs）を使用してください。

* UCS C-Series Rack ServersまたはX-Series Modularシステムを使用する場合は、冗長構成の2台のCisco UCS 6400、6500、または6600 Series Fabric Interconnectが必要です。
* Intersight管理構成（IMM）を備えたFI接続の2台のCisco UCS C シリーズラックサーバー、またはCisco IMM搭載のCisco UCS X シリーズ Direct、またはCisco Intersight管理構成（IMM）搭載のCisco UCS X シリーズ Modular。



NOTE: UCSラックサーバーをFI接続なしで使用している場合は、管理にCIMCまたはIntersightスタンドアロンモードを使用できます。

* 高可用性（HA）ペア構成の NetApp AFF、NetApp ASA、または NetApp FAS コントローラ 2 台を 2ノードクラスタとして導入します。NetApp AFX を使用する場合、最低 4 台の NetApp AFX コントローラが必要であり、1 ペアのクラスタ インターコネクト スイッチとともに 4 ノード HA クラスタとして導入します。
* 内蔵ディスク シェルフを持たないストレージコントローラには、最低1つの NetApp ディスク シェルフが必要です。

