---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, switches, fabric, interconnects, servers, storage, controllers 
summary: FlexPod データセンター構成には、スイッチ、ファブリックインターコネクト、サーバ、ネットアップストレージコントローラなど、最小限のハードウェア要件が含まれますが、これらに限定されません。 
---
= ハードウェアの最小要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
FlexPod データセンター構成には、スイッチ、ファブリックインターコネクト、サーバ、ネットアップストレージコントローラなど、最小限のハードウェア要件が含まれますが、これらに限定されません。

Cisco UCS サーバを使用する必要があります。事前検証済みの設計では、 C シリーズサーバと B シリーズサーバの両方を使用しています。Cisco Nexus ファブリックエクステンダ（ FEX ）は、 C シリーズサーバではオプションです。

FlexPod 構成には、ハードウェアに関する次の最小要件があります。

* 冗長構成の 2 台の Cisco Nexus スイッチこの構成は、 Cisco Nexus 5000 、 7000 、または 9000 シリーズの 2 台の冗長スイッチで構成できます。2 つのスイッチは同じモデルであり、同じ動作モードで設定する必要があります。
+
ACI アーキテクチャを導入する場合は、次の追加要件を確認する必要があります。

+
** Cisco Nexus 9000 シリーズスイッチをリーフスパイントポロジに導入する。
** 3 つの Cisco Application Policy Infrastructure Controller （ APIC; アプリケーションポリシーインフラストラクチャコントローラ）を使用します。


* 冗長構成の Cisco UCS 6200 、 6300 、または 6400 シリーズファブリックインターコネクト × 2
* Cisco UCS サーバ：
+
** 解決策が B シリーズサーバを使用する場合は、 Cisco UCS 5108 B シリーズブレードサーバシャーシ 1 台と Cisco UCS B シリーズブレードサーバ 2 台と、 2104 、 2204/8 、 2408 、または 2304 I/O モジュール（ IOM ） 2 台を合わせます。
** 解決策が C シリーズサーバを使用している場合は、 Cisco UCS C シリーズラックサーバを 2 台。
+
Cisco UCS C シリーズラックサーバをより大規模に導入する場合は、 2232PP FEX モジュールのペアを選択できます。ただし、 2232PP はハードウェア要件ではありません。



* ハイアベイラビリティ（ HA ）ペア構成のネットアップストレージコントローラ × 2 ：
+
この構成には、サポートされているネットアップの FAS 、 AFF 、または ASA シリーズのストレージコントローラが含まれます。を参照してください https://hwu.netapp.com/["NetApp Hardware Universe の略"^] サポートされている FAS 、 AFF 、 ASA の各コントローラモデルの最新リストを表示するためのアプリケーション。

+
** HA 構成では、データアクセス用にコントローラごとに 2 つの冗長インターフェイスが必要です。インターフェイスは FCoE 、 FC 、 10 / 25 / 100Gb イーサネット（ GbE ）です。
** 解決策で NetApp ONTAP を使用している場合は、ネットアップの承認を受けたクラスタインターコネクトトポロジが必要です。詳細については、を参照してください https://hwu.netapp.com/Switch/Index["スイッチ"^] NetApp Hardware Universe のタブ。
** 解決策が ONTAP を使用している場合、データアクセスには、コントローラごとに最低 2 つの 10 / 25 / 100GbE ポートが追加で必要です。
** 2 ノード構成の ONTAP クラスタでは、 2 ノードスイッチレスクラスタを構成できます。
** ONTAP クラスタのノードが 3 つ以上の場合は、クラスタインターコネクトスイッチのペアが必要です。


* サポート対象のディスクタイプが設定されたネットアップディスクシェルフ × 1のシェルフタブを参照してください link:https://hwu.netapp.com/Shelves/Index?osTypeId=2032["NetApp Hardware Universe の略"^] サポートされるディスクシェルフモデルの最新のリストについては、を参照してください。

