---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, cisco, ucs, fabric, interconnect, uplink, direct, san 
summary: FlexPod 構成の接続要件は次のとおりです。 
---
= 接続要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
FlexPod 構成には、次の接続要件があります。

* 独立した1Gbイーサネットのアウトオブバンド管理ネットワークが、すべてのコンポーネントに必要です。
* 環境全体でジャンボフレームのサポートを有効にすることを推奨しますが、必須ではありません。
* スタンドアロンCisco UCS Fabric Interconnectアプライアンスのポートは、iSCSI接続にのみ使用することを推奨します。アプライアンスポートでNAS接続を使用する場合、特定の障害シナリオに対応するため、追加のNexus / 準拠スイッチが必要になります。
* FlexPod のコアコンポーネント間に他の機器を配置することはできません。


アップリンク接続：

* NetAppストレージコントローラのポートは、仮想ポートチャネル（vPC）のサポートを有効にするために、Cisco Nexus 9000シリーズスイッチに接続する必要があります。
* vPC は、Cisco Nexus 9000 シリーズ スイッチから NetApp ストレージ コントローラへの接続に必要です。
* vPC は、Cisco Nexus 9000 シリーズ スイッチからファブリック インターコネクトへの接続に必要です。
* vPC には少なくとも 2 つの接続が必要です。アプリケーションの負荷とパフォーマンスの要件に基づいて、 vPC 内の接続数を増やすことができます。


直接接続：

* NetApp ファブリックインターコネクトに直接接続されているストレージコントローラポート（X-Series Direct の場合など）は、グループ化してポートチャネルを有効にすることができます。この構成では vPC はサポートされていません。
* FCoE エンドツーエンドの設計では、 FCoE ポートチャネルが推奨されます。


SAN ブート：

* FlexPod ソリューションは、 iSCSI 、 FC 、または FCoE プロトコルを使用する SAN ブートアーキテクチャを中心に設計されています。SAN からのブートテクノロジを使用すると、データセンターインフラの柔軟な構成が可能になり、各インフラコンポーネントで使用できる豊富な機能を使用できます。SAN からのブートは最も効率的な構成ですが、ローカルサーバストレージからのブートは有効でサポートされている構成です。
* FC-NVMe での SAN ブートはサポートされていません。


各トポロジーに固有の接続要件については、link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["FlexPod データセンターのトポロジー"^]セクションを参照してください。
