---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, cisco, ucs, fabric, interconnect, uplink, direct, san 
summary: FlexPod 構成の接続要件は次のとおりです。 
---
= 接続要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


FlexPod 構成には、次の接続要件があります。

* すべてのコンポーネントに対し、 100Mbps イーサネット / 1Gb イーサネットアウトオブバンド管理ネットワークがそれぞれ必要です。
* 環境全体でジャンボフレームのサポートを有効にすることを推奨しますが、必須ではありません。
* Cisco UCS ファブリックインターコネクトアプライアンスのポートは、 iSCSI 接続と NAS 接続にのみ使用することを推奨します。
* FlexPod のコアコンポーネント間に他の機器を配置することはできません。


アップリンク接続：

* 仮想ポートチャネル（ vPC ）をサポートするには、ネットアップストレージコントローラのポートを Cisco Nexus 5000 、 7000 、または 9000 シリーズスイッチに接続する必要があります。
* vPC は、 Cisco Nexus 5000 、 7000 、または 9000 シリーズスイッチとネットアップストレージコントローラの間で必要となります。
* vPC は、 Cisco Nexus 5000 、 7000 、または 9000 シリーズスイッチとファブリックインターコネクトの間で必要となります。
* vPC には少なくとも 2 つの接続が必要です。アプリケーションの負荷とパフォーマンスの要件に基づいて、 vPC 内の接続数を増やすことができます。


直接接続：

* ファブリックインターコネクトに直接接続されているネットアップストレージコントローラポートは、グループ化してポートチャネルを有効にすることができます。vPC はこの構成ではサポートされません。
* FCoE エンドツーエンドの設計では、 FCoE ポートチャネルが推奨されます。


SAN ブート：

* FlexPod ソリューションは、 iSCSI 、 FC 、または FCoE プロトコルを使用する SAN ブートアーキテクチャを中心に設計されています。SAN からのブートテクノロジを使用すると、データセンターインフラの柔軟な構成が可能になり、各インフラコンポーネントで使用できる豊富な機能を使用できます。SAN からのブートは最も効率的な構成ですが、ローカルサーバストレージからのブートは有効でサポートされている構成です。
* FC-NVMe での SAN ブートはサポートされていません。

