---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, switches, fabric, interconnects, servers, storage, controllers 
summary: FlexPod データセンター構成には、スイッチ、ファブリックインターコネクト、サーバ、ネットアップストレージコントローラなど、最小限のハードウェア要件が含まれますが、これらに限定されません。 
---
= ハードウェアの最小要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
FlexPod データセンター構成には、スイッチ、ファブリックインターコネクト、サーバ、ネットアップストレージコントローラなど、最小限のハードウェア要件が含まれますが、これらに限定されません。

FlexPod 構成には、ハードウェアに関する次の最小要件があります。

* 冗長構成の2台のCisco Nexusスイッチ。この構成は、前述のCisco Nexus 9000シリーズから2台の冗長スイッチで構成できます。2つのスイッチは同じモデルで、同じ動作モードで設定されている必要があります。



NOTE: ACIアーキテクチャをデプロイする場合は、次の追加要件を遵守する必要があります。* リーフスパイン型トポロジーを採用した Cisco Nexus 9000 シリーズスイッチをデプロイしてください。* 3つの Cisco Application Policy Infrastructure Controllers （APICs）を使用してください。

* UCS C-Series Rack ServersまたはX-Series Modularシステムを使用する場合は、冗長構成の2台のCisco UCS 6400、6500、または6600 Series Fabric Interconnectが必要です。
* Intersight Managed Mode （IMM） 構成の FI 接続を備えた 2 台の Cisco UCS C シリーズ ラック サーバー、または Cisco IMM を搭載した Cisco UCS X シリーズ ダイレクト、または Cisco IMM を搭載した Cisco UCS X シリーズ モジュラー。



NOTE: UCSラックサーバーをFI接続なしで使用している場合は、管理にCIMCまたはIntersightスタンドアロンモード（ISM）を使用できます。

* 高可用性（HA）ペア構成のNetApp AFF、NetApp ASA、またはNetApp FASコントローラ2台を2ノードクラスタとして導入します。NetApp AFXを使用する場合は、最低4台のNetApp AFXコントローラが必要であり、2つのHAペアとクラスタ インターコネクトスイッチのペアを備えた4ノードクラスタとして導入する必要があります。
* 内蔵ディスク シェルフを持たないストレージコントローラには、最低1つの NetApp ディスク シェルフが必要です。

