---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_nexus_switching_modes_of_operation.html 
keywords: cisco, nexus, nx-os, aci, switching, modes, operation, datacenter, technical, specifications 
summary: さまざまな Cisco Nexus 製品を、特定の FlexPod 展開のスイッチングコンポーネントとして使用できます。これらのオプションのほとんどは、Cisco NX-OS ソフトウェアを活用しています。Cisco Nexus ファミリのスイッチは、製品ラインにわたってさまざまな機能を提供しています。これらの機能については、本書の後半で詳しく説明します。 
---
= Cisco Nexus スイッチング動作モード
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
さまざまな Cisco Nexus 製品を、特定の FlexPod 展開のスイッチングコンポーネントとして使用できます。これらのオプションのほとんどは、Cisco NX-OS ソフトウェアを活用しています。Cisco Nexus ファミリのスイッチは、製品ラインにわたってさまざまな機能を提供しています。これらの機能については、本書の後半で詳しく説明します。

Ciscoのソフトウェアで定義されるネットワーキング分野における製品は、Application Centric Infrastructure（ACI）と呼ばれます。ACIモード（ファブリックモード）をサポートするCisco Nexus製品ラインは、NX-OSモードでも展開できます。


NOTE: すべての Cisco Nexus スイッチが ACI モードをサポートしているわけではありません。導入する特定のモデルが、運用上の要件を満たしていることを確認してください。

Cisco ACI は、特定のアプリケーションの要件に重点を置いたデータセンター導入をターゲットとしています。アプリケーションは、ホストまたは仮想マシン（ VM ）からネットワーク経由でストレージに接続できる一連のプロファイルと契約を通じてインスタンス化されます。

FlexPod データセンターは、NX-OSモードとACIモードの両方で動作するCisco Nexusスイッチで検証済みです。お客様は、自社のネットワークアーキテクチャ、運用モデル、および自動化要件に最適な運用モードを選択できます。ACIモードとNX-OSモードの詳細については、以下のCiscoページを参照してください：

* http://www.cisco.com/c/en/us/solutions/data-center-virtualization/application-centric-infrastructure/index.html["Cisco Application Centric Infrastructure の場合"^]
* https://www.cisco.com/site/us/en/products/networking/cloud-networking/nx-os/index.html["Cisco NX-OS ソフトウェア"^]

