---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, fas, cimc, configuration, rack, servers, ucs 
summary: ここでは、 FlexPod Express の各バージョンに必要なハードウェアの最小要件について説明します。 
---
= ハードウェアの最小要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ここでは、 FlexPod Express の各バージョンに必要なハードウェアの最小要件について説明します。



== FlexPod Express with NetApp FAS 』を参照してください

基盤となるストレージにネットアップの FAS コントローラを使用する FlexPod Express ソリューションのハードウェア要件として、このセクションで説明する構成があります。



=== CIMC ベースの設定（スタンドアロンラックサーバ）

Cisco Integrated Management Controller （ CIMC ）の設定には、次のハードウェアコンポーネントが含まれています。

* 冗長構成の 10Gbps 標準イーサネットスイッチ × 2 （ Cisco Nexus 0808 を推奨、 Cisco Nexus 3000 モデルと 9000 モデルをサポート）
* Cisco UCS C シリーズスタンドアロンラックサーバ
* AFF C190 、 AFF A250 、 FAS2600 、または FAS 2700 シリーズのコントローラが 2 ノードクラスタとして導入されたハイアベイラビリティ（ HA ）ペア構成で 2 台




=== Cisco UCS で管理される構成

Cisco UCS が管理する確認には、次のハードウェアコンポーネントが含まれます。

* 冗長構成の 10Gbps 標準イーサネットスイッチ × 2 （ Cisco Nexus 3524 を推奨）
* Cisco UCS 5108 交流（ AC ）ブレードサーバシャーシ 1 台
* Cisco UCS 6324 ファブリックインターコネクト × 2
* Cisco UCS B シリーズサーバ（ Cisco UCS B200 M5 ブレードサーバ × 4 以上）
* HA ペア構成の AFF C190 、 AFF A250 、 FAS2750 、 FAS2720 コントローラ × 2 （コントローラごとに使用可能なユニファイドターゲットアダプタ 2 つ UTA2 ポートが 2 つ必要）




== FlexPod Express と E シリーズ

E シリーズのスターター構成を使用した FlexPod Express のハードウェア要件は次のとおりです。

* Cisco UCS 6324 ファブリックインターコネクト × 2
* Cisco UCS Mini シャーシ 5108 AC2 または DC2 （ Cisco UCS 6324 ファブリックインターコネクトは AC2 および DC2 シャーシでのみサポート）
* Cisco UCS B シリーズサーバ（ Cisco UCS B200 M4 ブレードサーバ × 2 以上）
* E シリーズ E2824 ストレージシステムの HA ペア構成 × 1 。 12 本以上のディスクドライブを搭載
* 冗長構成の 10Gbps 標準イーサネットスイッチ × 2 （データセンター内の既存のスイッチを使用可能）


これらのハードウェアコンポーネントは、解決策のスターター構成を構築するために必要です。必要に応じて、ブレードサーバとディスクドライブを追加できます。E シリーズ E2824 ストレージシステムは、上位のプラットフォームに交換することも、オールフラッシュシステムとして実行することもできます。
