---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: NetAppストレージコントローラは、FlexPod Expressアーキテクチャにおいて、ブートデータとアプリケーションデータの両方のストレージ基盤を提供します。このセクションでは、FlexPod ExpressアーキテクチャにおけるさまざまなNetAppストレージオプションを記載しています。 
---
= NetApp コンポーネント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
ネットアップストレージコントローラは、ブートとアプリケーションデータストレージの両方を実現する FlexPod Express アーキテクチャのストレージ基盤を提供します。このセクションでは、 FlexPod Express アーキテクチャのさまざまなネットアップオプションについて説明します。



[[netapp-storage-controller-options]]
== ネットアップストレージコントローラのオプション

FlexPod Expressアーキテクチャには、冗長化されたAFF、ASA、またはFASシリーズコントローラが必要です。コントローラはONTAPソフトウェアを実行します。ストレージコントローラを注文する際、希望するソフトウェアバージョンをコントローラにプリロードすることができます。ONTAPの場合、クラスタはクラスタ インターコネクトスイッチのペアを使用してデプロイするか、スイッチレスクラスタ構成でデプロイすることができます。


NOTE: スイッチレスクラスタ構成は、2ノード構成の場合のみサポートされます。クラスタ インターコネクト スイッチは、4ノードを超える構成では必須であり、2ノード構成ではオプションです。

選択したストレージ プラットフォームに応じて、さまざまなオプションと構成が利用可能です。これらの追加部品の詳細については、担当の営業担当者にお問い合わせください。

下記の表に記載されているコントローラファミリは、Cisco Nexusスイッチへの接続がシームレスであるため、FlexPodソリューションでの使用に適しています。各コントローラモデルの具体的な互換性の詳細については、 http://hwu.netapp.com/["NetApp Hardware Universe の略"^]を参照してください。

|===
| NetAppのFlexPod Express向けエントリレベル ストレージ ファミリ | モデル | 技術仕様 


.2+| AFF A シリーズ | A20を使用したチャンク アップロード署名要求がサポートされるようになりました。 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["AFF A-Series のドキュメント"] 


| A30を使用したチャンク アップロード署名要求がサポートされるようになりました。 


| AFF Cシリーズ | C30を使用したチャンク アップロード署名要求がサポートされるようになりました。 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["AFF Cシリーズのドキュメント"] 


.2+| ASA Aシリーズ | A20を使用したチャンク アップロード署名要求がサポートされるようになりました。 .3+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA ドキュメント"] 


| A30を使用したチャンク アップロード署名要求がサポートされるようになりました。 


| ASA Cシリーズ | C30を使用したチャンク アップロード署名要求がサポートされるようになりました。 


.3+| FAS | FAS 2750 .3+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS ドキュメント"] 


| FAS 2820 


| FAS 50 
|===


[[netapp-disk-shelves-and-disks]]
== ネットアップのディスクシェルフとディスク

内蔵ディスク シェルフを持たないストレージコントローラには、最低1つの NetApp ディスク シェルフが必要です。選択された NetApp ディスク シェルフのタイプによって、そのシェルフ内で使用可能なドライブの種類が決まります。


NOTE: すべてのディスクシェルフとディスクのパーツ番号については、営業担当者にお問い合わせください。

以下の表に、NetApp の FlexPod Express 向けディスク シェルフ オプションと、その技術仕様へのリンクを示します。

お使いのディスク シェルフでサポートされているドライブの一覧を取得するには、link:https://hwu.netapp.com/DetailViews/Home.aspx["NetApp Hardware Universe の略"^]にアクセスし、「製品 > ストレージ > シェルフ」で「ONTAP （AFF、ASA、FAS）」を選択し、使用している ONTAP のバージョンを選択してから、シェルフの種類（例：「DS212C」）を選択して「結果を表示」をクリックします。「サポートされているドライブ」をクリックすると、特定のバージョンの ONTAP およびディスク シェルフでサポートされているドライブが表示されます。

|===
| ディスクシェルフ | 技術仕様 


| DS212C .5+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["ディスク シェルフとストレージ メディア"] 


| DS224C 


| DS460C 


| NS224 


| NS224 w/NSM100B 
|===


[[netapp-software-licensing-options]]
== ネットアップのソフトウェアライセンスオプション

以下の表は、NetAppソフトウェアライセンスのオプションを示しています。

|===
| ネットアップソフトウェアライセンス | 技術仕様 


| ONTAP One（AFF および FAS 向け） .2+| ライセンスについて詳しくは、ネットアップの営業チームにお問い合わせください。 


| ASA用ONTAP One for SAN 
|===
NetApp ソフトウェア ライセンスの詳細については、次のリンクを参照してください： https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ネットアップソフトウェアライセンス"^]。



[[netapp-support-licensing-options]]
== ネットアップサポートのライセンスオプション

SupportEdge Premium ライセンスが必要です。これらのライセンスのパーツ番号は、 FlexPod Express デザインで選択されたオプションによって異なります。

次の表に、NetApp AFF、ASA、FASストレージシステムのNetAppサポートライセンスオプションを示します。

|===
| ネットアップサポートライセンス | 技術仕様 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===