---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec__netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: NetAppストレージコントローラは、FlexPod Expressアーキテクチャにおいて、ブートデータとアプリケーションデータの両方のストレージ基盤を提供します。このセクションでは、FlexPod ExpressアーキテクチャにおけるさまざまなNetAppストレージオプションを記載しています。 
---
= NetApp コンポーネント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
ネットアップストレージコントローラは、ブートとアプリケーションデータストレージの両方を実現する FlexPod Express アーキテクチャのストレージ基盤を提供します。このセクションでは、 FlexPod Express アーキテクチャのさまざまなネットアップオプションについて説明します。



== ネットアップストレージコントローラのオプション

FlexPod Expressアーキテクチャには、冗長化されたAFF、ASA、またはFASシリーズコントローラが必要です。コントローラはONTAPソフトウェアを実行します。ストレージコントローラを注文する際、希望するソフトウェアバージョンをコントローラにプリロードすることができます。ONTAPの場合、クラスタ インターコネクトスイッチのペアを使用するか、スイッチレスクラスタ構成でクラスタを導入できます。


NOTE: スイッチレスクラスタ構成は、2ノード構成の場合のみサポートされます。クラスタ インターコネクト スイッチは、4ノードを超える構成では必須であり、2ノード構成ではオプションです。

選択したストレージプラットフォームに応じて、さまざまなオプションと構成が利用可能です。これらの追加コンポーネントの詳細については、営業担当者にお問い合わせください。

下記の表に記載されているコントローラファミリは、Cisco Nexusスイッチへの接続がシームレスであるため、FlexPodソリューションでの使用に適しています。各コントローラモデルの具体的な互換性の詳細については、 http://hwu.netapp.com/["NetApp Hardware Universe の略"^]を参照してください。

|===
| NetAppのFlexPod Express向けエントリレベル ストレージ ファミリ | モデル | 技術仕様 


.2+| AFF A シリーズ | A20を使用したチャンク アップロード署名要求がサポートされるようになりました。 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["AFF A-Series のドキュメント"] 


| A30 


| AFF Cシリーズ | C30を使用したチャンク アップロード署名要求がサポートされるようになりました。 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["AFF Cシリーズのドキュメント"] 


.2+| ASA Aシリーズ | A20を使用したチャンク アップロード署名要求がサポートされるようになりました。 .2+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA Aシリーズのドキュメント"] 


| A30 


| ASA Cシリーズ | C30を使用したチャンク アップロード署名要求がサポートされるようになりました。 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA Cシリーズのドキュメント"] 


.2+| FAS | FAS 2750 .2+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS ドキュメント"] 


| FAS 2820 
|===


== ネットアップのディスクシェルフとディスク

ストレージ コントローラには、最低 1 つの NetApp ディスク シェルフが必要です。

選択したネットアップシェルフタイプによって、そのシェルフ内で使用可能なドライブタイプが決まります。


NOTE: すべてのディスクシェルフとディスクのパーツ番号については、営業担当者にお問い合わせください。

サポートされているドライブの詳細については、次の表の「 NetApp Hardware Universe 」リンクをクリックし、サポートされているドライブを選択してください。

次の表に、ネットアップのディスクシェルフオプションと、 NetApp Hardware Universe に搭載されている各シェルフタイプでサポートされるドライブを示します。Hardware Universe リンクに従って、使用している ONTAP のバージョンを選択し、シェルフタイプを選択します。シェルフイメージの下の Supported Drives をクリックすると、特定のバージョンの ONTAP およびディスクシェルフでサポートされるドライブが表示されます。

|===
| ディスクシェルフ | 技術仕様 


| DS212C .5+| https://hwu.netapp.com/DetailViews/Home.aspx["NetApp Hardware Universe でサポートされているディスクシェルフとストレージメディアドライブ"] 


| DS224C 


| DS460C 


| NS224 


| NS224 w/NSM100B 
|===


== ネットアップのソフトウェアライセンスオプション

以下の表は、NetAppソフトウェアライセンスのオプションを示しています。

|===
| ネットアップソフトウェアライセンス | 技術仕様 


| AFFおよびFAS向けのONTAP OneまたはONTAP Base .2+| ライセンスについて詳しくは、ネットアップの営業チームにお問い合わせください。 


| ASA用ONTAP One for SAN 
|===


== ネットアップサポートのライセンスオプション

SupportEdge Premium ライセンスが必要です。これらのライセンスのパーツ番号は、 FlexPod Express デザインで選択されたオプションによって異なります。

次の表に、NetApp AFF、ASA、FASストレージシステムのNetAppサポートライセンスオプションを示します。

|===
| ネットアップサポートライセンス | パーツ番号 | 技術仕様 


| SupportEdge Premium4 時間オンサイト、月数 :36 | ： cs -O2-4HR | link:https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf["https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf"] 
|===