---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, flexpod, express, aff, fas, e, series 
summary: ここでは、 FlexPod Express の各バージョンの接続要件について説明します。 
---
= 接続要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
ここでは、 FlexPod Express の各バージョンの接続要件について説明します。



== NetApp FASを使用したFlexPod Expressの接続要件

NetApp FASを使用したFlexPod Expressの接続要件は次のとおりです。

* NetApp FAS ストレージコントローラは、Cisco UCS 管理構成を除き、Cisco Nexus スイッチに直接接続する必要があります。Cisco UCS 管理構成では、ストレージコントローラはファブリック インターコネクトに接続されます。
* FlexPod のコアコンポーネント間には、追加の機器をインラインで配置できません。
* 仮想ポートチャネル（vPC）は、Cisco Nexus 3000/9000シリーズスイッチをNetAppストレージコントローラに接続するために必要です。
* 必須ではありませんが、環境全体でジャンボフレームのサポートを有効にすることを推奨します。




== NetApp Eシリーズを搭載したFlexPod Expressの接続要件

FlexPod Express と Eシリーズの接続要件は次のとおりです：

* Eシリーズ ストレージ コントローラは、ファブリック インターコネクトに直接接続する必要があります。
* コアの FlexPod コンポーネント間に追加の機器をインラインで配置しないでください。
* ファブリック インターコネクトとイーサネット スイッチの間には vPC が必要です。




== FlexPod Express with NetApp AFF の接続要件

NetApp AFFを使用したFlexPod Expressの接続要件は次のとおりです。

* NetApp AFF ストレージコントローラは、Cisco UCS 管理構成を除き、Cisco Nexus スイッチに直接接続する必要があります。Cisco UCS 管理構成では、ストレージコントローラはファブリック インターコネクトに接続されます。
* FlexPod のコアコンポーネント間には、追加の機器をインラインで配置できません。
* 仮想ポートチャネル（vPC）は、Cisco Nexus 3000/9000シリーズスイッチをNetAppストレージコントローラに接続するために必要です。
* 必須ではありませんが、環境全体でジャンボフレームのサポートを有効にすることを推奨します。

