---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, express, cisco, ucs, cabling 
summary: このセクションでは、FlexPod Express 設計の電源要件とディスク シェルフのケーブル接続ガイドラインについて説明します。 
---
= 電源およびケーブル配線に関するガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このセクションでは、FlexPod Express 設計の電源要件とケーブル配線ガイドラインについて説明します。



== 電力要件

FlexPod Express の電力要件は、FlexPod Express 構成がインストールされる場所によって異なります。

必要な最大電力に関するデータやその他の詳細な電力情報については、各ハードウェア コンポーネントのlink:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_technical_specifications_and_references.html["技術仕様"^]を参照してください。

Cisco UCS の電力データの詳細については、を参照してください http://www.cisco.com/assets/cdc_content_elements/flash/dataCenter/cisco_ucs_power_calculator/["Cisco UCS Power Calculator"^]。

NetAppストレージコントローラの電源データについては、 http://hwu.netapp.com/Controller/Index?platformTypeId=6780858["NetApp Hardware Universe の略"^]を参照してください。*Platforms* で、使用するストレージ プラットフォーム（例：AFF A20）を選択し、ONTAP バージョンを選択して、*Show Results* をクリックします。電源コードのデータは *Supported Power Cords* セクションに記載されています。サイズ、重量、ワット数などの詳細については、*Size, Weight, Acoustic, Power* セクションを参照してください。



== ケーブル配線ガイドライン

このセクションでは、FlexPod Express 設計の一般的なケーブル配線ガイドラインを説明します。

* コンピューティングおよびストレージ接続において、冗長な接続性を確保してください。
* 接続速度は、接続される機器の速度と互換性がある必要があります。
* 特定のトポロジーに関する追加のケーブル配線ガイドラインについては、link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["FlexPod Express トポロジー"^]セクションを参照してください。


次の表に、FlexPod Express設計で使用できるNetAppディスク シェルフのケーブル接続ガイドラインを示します。

|===


| ディスクシェルフ | ケーブル配線ガイドライン 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["SASケーブル配線規則"^] 


| DS224C 


| DS460C 


| NS224 .2+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["NS224 シェルフの要件とベストプラクティス"^] 


| NS224 w/NSM100B 
|===