---
sidebar: sidebar 
permalink: hybrid-cloud/cloud-insights_use_cases.html 
keywords: target, cases, audience, cloud, insights, flexpod, ontap 
summary: この解決策を適用する対象となる対象となる対象となるユーザとケースをこのセクションに記載します。 
---
= ユースケース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
この解決策環境のユースケースは次のとおりです。

* FlexPod 解決策の一部として導入された ONTAP ストレージシステムのさまざまなリソースと使用率を監視する必要がある組織。
* AFF または FAS システムを使用して FlexPod 解決策で発生したインシデントのトラブルシューティングを行い、解決時間を短縮したいと考えている組織。
* コストの最適化を検討している組織では、無駄なリソースに関する詳細な情報を提供するカスタマイズされたダッシュボードや、 ONTAP などの FlexPod 環境でコスト削減を実現できる場所などが挙げられます。




== 対象読者

解決策の対象となるグループは次のとおりです。

* コストの最適化とビジネス継続性に関心を持つ IT エグゼクティブとその関係者。
* データセンターやハイブリッドクラウドの設計と管理に関心のあるソリューションアーキテクト。
* トラブルシューティングとインシデント解決を担当するテクニカルサポートエンジニア。


Cloud Insights は、計画、トラブルシューティング、メンテナンス、およびビジネス継続性の確保に役立ついくつかの有用なデータタイプを提供するように設定できます。FlexPod Datacenter 解決策 with Cloud Insights を監視し、集計データをわかりやすいカスタマイズされたダッシュボードに表示することで、 ニーズに応じて環境内のリソースをいつ拡張する必要があるかを予測できるだけでなく、システム内で問題の原因となっている特定のアプリケーションやストレージボリュームを特定することもできます。これにより、監視対象のインフラストラクチャが予測可能で、期待どおりに動作することが保証されます。これにより、組織は定義済みの SLA を提供し、必要に応じてインフラストラクチャを拡張できるようになり、無駄と追加コストを削減できます。
