---
sidebar: sidebar 
permalink: hybrid-cloud/cloud-fabricpool_set_volume_tiering_minimum_cooling_days.html 
keywords: volume, tiering, minimum, cooling, days, set, auto, ontap, cli, snapshot 
summary: 階層化の最小クーリング日数設定は、「自動」または「 Snapshot のみ」ポリシーを使用するボリューム内のアクセス頻度の低いデータがコールドとみなされて階層化の対象となるまでの日数を決定します。 
---
= ボリューム階層化の最小クーリング日数を設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


「 tiering-minimum-cooling-days 」設定では、ボリューム内のアクセス頻度の低いデータがコールドとみなされて階層化の対象になるまでの日数を指定します。



== 自動

Auto 階層化ポリシーのデフォルトの「 tiering-minimum-cooling-days 」設定は 31 日です。

読み取りではブロック温度がホットになるため、この値を大きくすると、階層化の対象となるデータ量が減り、パフォーマンス階層に保持されるデータ量が増加する可能性があります。

この値をデフォルトの 31 日間から減らす場合は、コールドとしてマークされる前にデータをアクティブにしないようにしてください。たとえば ' 複数日のワークロードが 7 日目にかなりの数の書き込みを実行すると予想される場合 ' ボリュームの「 tiering-minimum-cooling-days 」設定は 8 日以上に設定する必要があります


NOTE: オブジェクトストレージは、ファイルやブロックストレージのようにトランザクション可能ではありません。ボリュームにオブジェクトとして保存されているファイルを変更してクーリング日数を最小限に抑えると、新しいオブジェクトの作成、既存のオブジェクトの断片化、およびストレージの非効率性の追加につながる可能性があります。



== Snapshot のみ

スナップショット専用階層化ポリシーのデフォルトの「 tiering-minimum-cooling-days 」設定は 2 日です。最小値を 2 日間に設定すると、バックグラウンドプロセスの時間が長くなり、ストレージ効率が最大限に向上します。また、日々のデータ保護プロセスがクラウド階層からデータを読み取る必要がなくなります。



== ONTAP CLI

ONTAP CLI を使用してボリュームの「 tiering-minimum-cooling-days 」設定を変更するには、次のコマンドを実行します。

....
volume modify -vserver <svm_name> -volume <volume_name> -tiering-minimum-cooling-days <2-63>
....
advanced 権限レベルが必要です。


NOTE: 階層化ポリシーを「自動」と「 Snapshot のみ」（またはその逆）の間で変更すると、パフォーマンス階層のブロックの非アクティブ期間がリセットされます。たとえば、「自動」ボリューム階層化ポリシーを使用し、 20 日間非アクティブだったパフォーマンス階層のデータを含むボリュームでは、階層化ポリシーが「 Snapshot のみ」に設定されている場合、パフォーマンス階層のデータが非アクティブになる日数は 0 日にリセットされます。
