---
sidebar: sidebar 
permalink: hybrid-cloud/fhc-cvoe-conclusion.html 
keywords: conclusion 
summary: ほとんどの医療機関では、ハイブリッドクラウドの構築が、いつでもデータにアクセスできるようにすることを目標としています。この解決策 では、Cloud Volumes ONTAP を備えたFlexPod ハイブリッドクラウド解決策 を実装し、ネットアップのSnapMirrorレプリケーションテクノロジを活用して、ヘルスケアアプリケーションとワークロードのバックアップとリカバリのいくつかのユースケースを検証しました。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:fhc-cvoe-solution-validation.html["前のバージョン：解決策 の検証。"]

[role="lead"]
ほとんどの医療機関では、ハイブリッドクラウドの構築が、いつでもデータにアクセスできるようにすることを目標としています。この解決策 では、Cloud Volumes ONTAP を備えたFlexPod ハイブリッドクラウド解決策 を実装し、ネットアップのSnapMirrorレプリケーションテクノロジを活用して、ヘルスケアアプリケーションとワークロードのバックアップとリカバリのいくつかのユースケースを検証しました。

FlexPod は、Ciscoとネットアップの戦略的パートナーシップが提供する厳格なテストと検証済みの統合インフラです。予測可能な低レイテンシのシステムパフォーマンスと高可用性を実現するように設計されています。このアプローチにより、EHRの快適性レベルが高くなり、最終的にEHRシステムのユーザーにとって最適な応答時間が得られます。

ネットアップなら、オンプレミスのデータセンターでネットアップのストレージ機能を実行するのと同じように、本番環境のEHR、ディザスタリカバリ、バックアップ、階層化をクラウドで実行できます。ネットアップは、NetApp Cloud Volumes ONTAP を使用して、クラウドでEHRを効果的に実行するために必要なエンタープライズクラスの機能とパフォーマンスを提供します。ネットアップのクラウドオプションは、iSCSI経由のブロックとNFSまたはSMB経由のファイルを提供します。

この解決策 は、医療機関のニーズに応え、デジタル変革に向けた一歩を踏み出すためのものです。また、アプリケーションやワークロードを効率的に管理するのにも役立ちます。

link:fhc-cvoe-where-to-find-additional-information.html["次へ：追加情報の検索場所。"]
