---
sidebar: sidebar 
permalink: vdi/fpd-citrix-vir.html 
keywords: flexpod, cisco, data, center, citrix, virtual, apps, vmware, vsphere 
summary: 本ドキュメントでは、最大6、000人のエンドユーザコンピューティングユーザを対象とした仮想デスクトップインフラのアーキテクチャと設計について説明します。 
---
= FlexPod Datacenter with Citrix Virtual Apps & Desktops 1912 LTSR and VMware vSphere 7（最大6000シート
:allow-uri-read: 


Jeff Nichols、Cisco Suresh Thoppay、ネットアップDre Jackson

本ドキュメントでは、最大6、000人のエンドユーザコンピューティングユーザを対象とした仮想デスクトップインフラのアーキテクチャと設計について説明します。解決策 は、第5世代のCisco UCS B200 M5ブレードサーバ上に仮想化され、AFF A400ストレージアレイからFC SAN経由でVMware vSphere 7.01 Update 1をブートします。仮想デスクトップは、Citrix Provisioning Server 1912 LTSRとCitrix RDS/Citrix Virtual Apps & Desktops 1912 LTSRを使用して、RDSでホストされる共有デスクトップ（6000）、プールまたはノンパーシステントホストの仮想Windows 10デスクトップ（5000）、 また、Citrix Machine Creation Services（5000）でプロビジョニングされたパーシステントホスト型仮想Windows 10デスクトップで、ユーザ数をサポートします。該当する場合は、この解決策 をお客様に導入する際のベストプラクティスの推奨事項とサイジングガイドラインを記載します。

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/cisco_ucs_ctx1912esxi7u1_flexpodV2.html["FlexPod Datacenter with Citrix Virtual Apps Desktops 1912 LTSR and VMware vSphere 7（最大6000シート"^]
