---
sidebar: sidebar 
permalink: flexpod-dc/fpd-cisco-vsphere.html 
keywords: flexpod, cisco, data, center, ontap, ucs, xeon, vmware, vsphere, aff 
summary: 'このドキュメントでは、NetApp ONTAP 9.6を搭載したCiscoとNetApp FlexPod データセンター、第2世代Intel Xeonスケーラブルプロセッサを搭載したCisco UCS Manager Unifiedソフトウェアリリース4.0(4)、およびVMware vSphere 6.7 U2について説明します。' 
---
= FlexPod データセンターには、VMware vSphere 6.7 U2、Cisco UCS第4世代ファブリック、NetApp ONTAP 9.6が搭載されています
:allow-uri-read: 


John George、Cisco Sree Lakshmi Lanka、ネットアップ

このドキュメントでは、NetApp ONTAP 9.6を搭載したCiscoとNetApp FlexPod データセンター、第2世代Intel Xeonスケーラブルプロセッサを搭載したCisco UCS Manager Unifiedソフトウェアリリース4.0(4)、およびVMware vSphere 6.7 U2について説明します。Cisco UCS Manager（UCSM）4.0(4)は、次の機能を統合的にサポートします。

* 現行のすべてのCisco UCSファブリックインターコネクトモデル：6200、6300、6324（Cisco UCS Mini）
* 6454
* 2200/2300/2400シリーズIOM
* Cisco UCS B-Series
* Cisco UCS Cシリーズ：


FlexPod Datacenter with NetApp ONTAP 9.6、Cisco UCSユニファイドソフトウェアリリース4.0(4)、およびVMware vSphere 6.7 U2は、Cisco Unified Computing System（Cisco UCS）、Cisco Nexus 9000スイッチファミリ、MDS 9000マルチレイヤファブリックスイッチを基盤とした、設計済みのベストプラクティスに基づくデータセンターアーキテクチャです。 およびONTAP 9を実行するNetApp AFF Aシリーズストレージアレイ。

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_vmware_netappaffa_u2.html["VMware vSphere 6.7 U2、Cisco UCS第4世代ファブリック、NetApp ONTAP 9.6を搭載したFlexPod データセンター"^]
