---
sidebar: sidebar 
permalink: flexpod-dc/sm-bcs-conclusion.html 
keywords: conclusion 
summary: SM-BC を備えた FlexPod データセンターは、アクティブ / アクティブのデータセンター設計を使用して、ビジネスクリティカルなワークロードのビジネス継続性とディザスタリカバリを実現します。解決策 は通常、地理的に分散した別々の場所に導入された 2 つのデータセンターをメトロエリア内で相互接続します。NetApp SM-BC 解決策 は、同期レプリケーションを使用して、ビジネスクリティカルなデータサービスをサイト障害から保護します。解決策 では、 2 つの FlexPod 配置サイトのラウンドトリップネットワークレイテンシが 10 ミリ秒未満である必要があります。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:sm-bcs-validated-scenarios.html["前のバージョン：解決策 の検証済みのシナリオ"]

[role="lead"]
SM-BC を備えた FlexPod データセンターは、アクティブ / アクティブのデータセンター設計を使用して、ビジネスクリティカルなワークロードのビジネス継続性とディザスタリカバリを実現します。解決策 は通常、地理的に分散した別々の場所に導入された 2 つのデータセンターをメトロエリア内で相互接続します。NetApp SM-BC 解決策 は、同期レプリケーションを使用して、ビジネスクリティカルなデータサービスをサイト障害から保護します。解決策 では、 2 つの FlexPod 配置サイトのラウンドトリップネットワークレイテンシが 10 ミリ秒未満である必要があります。

第 3 のサイトに導入された NetApp ONTAP メディエーターは、 SM-BC 解決策 を監視し、サイト障害が検出されると自動フェイルオーバーを可能にします。VMware HA 構成および拡張された VMware vSphere Metro Storage Cluster 構成と NetApp SM-BC をシームレスに連携させて、解決策 が目的のゼロ RPO とほぼゼロ RTO 目標を達成できるようにします。

FlexPod SM-BC 解決策 は、要件を満たしている場合には既存の FlexPod インフラにも導入できます。また、既存の FlexPod に FlexPod 解決策 を追加してビジネス継続性の目標を達成することもできます。管理、監視、自動化のための Cisco Intersight 、 Ansible 、橋本テルクラフォームベースの自動化などの追加ツールがネットアップと Cisco から提供されるため、解決策 の監視や運用に関する分析情報の取得、導入と運用の自動化を簡単に行うことができます。

Microsoft SQL Server などのビジネスクリティカルなアプリケーションの観点からは、 ONTAP SM-BC CG 関係で保護された VMware データストア上にあるデータベースは、サイトストレージが停止しても引き続き使用できます。検証テストで確認したように、データベースが存在するストレージクラスタの停電後、 SM-BC CG 関係のフェイルオーバーが発生し、 Microsoft SQL Server トランザクションがアプリケーションを停止することなく再開します。

アプリケーション単位のきめ細かなデータ保護により、ビジネスクリティカルなアプリケーション向けに ONTAP SM-BC CG 関係を作成して、 RPO ゼロや RTO ほぼゼロの要件を満たすことができます。Microsoft SQL Server アプリケーションが実行されている VMware クラスタがサイトストレージの停止時にも運用を継続できるように、各サイトの ESXi ホストのブート LUN も SM-BC CG 関係によって保護されます。

FlexPod の柔軟性と拡張性により、ビジネス要件の変化に応じて拡張および拡張できる適切なサイズのインフラから始めることができます。この検証済みの設計により、 VMware vSphere ベースのプライベートクラウドを分散型統合インフラに確実に導入できるため、単一点障害の多いシナリオや、重要なビジネスデータサービスを保護するためのサイト障害に対して耐障害性のある解決策 を提供できます。

link:sm-bcs-where-to-find-additional-information-and-version-history.html["次へ：追加情報 およびバージョン履歴の参照先。"]
