---
sidebar: sidebar 
permalink: security/flexpod-fips-overview-of-fips-140-2.html 
keywords: fips 120-2, cryptographic module, security level, 
summary: FIPS 140-2 は、コンピュータや通信システムの機密情報を保護するセキュリティシステム内で使用される暗号モジュールのセキュリティ要件を規定しています。 
---
= FIPS 140-2 の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-cybersecurity-threats-in-healthcare.html["前の記事：医療業界におけるサイバーセキュリティの脅威。"]

https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.140-2.pdf["FIPS 140-2"^] コンピュータおよび通信システムの機密情報を保護するセキュリティシステム内で使用される暗号モジュールのセキュリティ要件を指定します。暗号モジュールは、ハードウェア、ソフトウェア、ファームウェア、またはその組み合わせのセットである必要があります。FIPS 環境 暗号化アルゴリズム、キー生成、および暗号化境界内に含まれるキー管理ツール。FIPS 140-2 は、製品、アーキテクチャ、データ、エコシステムではなく、暗号モジュールに適用される点に注意してください。暗号モジュールは、このドキュメントで後述する重要な用語で定義されており、承認されたセキュリティ機能を実装する特定のコンポーネント（ハードウェア、ソフトウェア、ファームウェアのいずれか）です。また、 FIPS 140-2 では 4 つのレベルが規定されています。承認された暗号化アルゴリズムは、すべてのレベルで共通です。各セキュリティレベルの主な要素と要件は次のとおりです。

* * セキュリティレベル 1 *
+
** 暗号モジュールの基本的なセキュリティ要件を指定します（少なくとも 1 つの承認されたアルゴリズムまたはセキュリティ機能が必要です）。
** レベル 1 には、本番グレードのコンポーネントの基本要件を超える物理的なセキュリティメカニズムは必要ありません。


* * セキュリティレベル 2 *
+
** コーティングやシール、取り外し可能なカバーや暗号モジュールのドアのロックなどの不正開封防止ソリューションを使用して、改ざん防止の要件を追加することで、物理的なセキュリティメカニズムを強化します。
** 少なくとも、ロールベースアクセスコントロール（ RBAC ）が必要です。この RBAC では、暗号化モジュールがオペレータまたは管理者の許可を認証して、特定のロールを引き受け、対応する一連の機能を実行します。


* * セキュリティレベル 3 *
+
** レベル 2 の不正改ざん防止要件を基に構築され、暗号化モジュール内の重要なセキュリティパラメータ（ CSP ）へのアクセスを防止しようとします。
** レベル 3 で必要とされる物理的なセキュリティメカニズムは、物理的なアクセス、または暗号モジュールの使用または変更の試みを検出して応答する可能性が高いことを目的としています。たとえば、強力なエンクロージャ、改ざん検出、応答回路などがあり、暗号モジュールの取り外し可能なカバーを開いたときにすべてのプレーンテキスト CSP をゼロにします。
** レベル 2 で指定された RBAC メカニズムのセキュリティを強化するために、 ID ベースの認証メカニズムが必要です。暗号モジュールは、オペレータの ID を認証し、オペレータが役割を使用して役割の機能を実行する権限を持っていることを確認します。


* * セキュリティレベル 4 *
+
** FIPS 140-2 で最高レベルのセキュリティ。
** 物理的に保護されていない環境での処理に最も有効なレベルです。
** このレベルでは、物理的なセキュリティメカニズムは、物理的なアクセスでの不正な試みを検出して応答する責任を持つ、暗号モジュールに関する完全な保護を提供することを目的としています。
** 暗号モジュールの侵入や露出は検出の可能性が高く、セキュアでない CSP やプレーンテキスト CSP がすべて初期化される可能性が高くなります。




link:flexpod-fips-control-plane-versus-data-plane.html["次に、コントロールプレーンとデータプレーンを比較します。"]
