---
sidebar: sidebar 
permalink: security/flexpod-fips-where-to-find-additional-information.html 
keywords:  
summary:  
---
= 確認応答、バージョン履歴、および追加情報 の参照先
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-conclusion.html["前へ：終わりに。"]

[role="lead"]
このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* 『 Cisco MDS 9000 Family NX-OS Security Configuration Guide 』
+
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/sw/8_x/config/security/cisco_mds9000_security_config_guide_8x/configuring_fips.html#task_1188151[]

* Cisco Nexus 9000 Series NX-OS Security Configuration Guide 、 Release 9.3(x)
+
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/security/configuration/guide/b-cisco-nexus-9000-nx-os-security-configuration-guide-93x/m-configuring-fips.html[]

* NetApp and Federal Information Processing Standard （ FIPS ） 140-2 』を参照できます
+
https://www.netapp.com/company/trust-center/compliance/fips-140-2/[]

* FIPS 140-2
+
https://fieldportal.netapp.com/content/902303[]

* 『 NetApp ONTAP 9 Hardening Guide 』
+
https://www.netapp.com/us/media/tr-4569.pdf[]

* NetApp Encryption パワーガイド』を参照してください
+
https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.pow-nve%2Fhome.html[]

* NVE および NAE のデータシート
+
https://www.netapp.com/us/media/ds-3899.pdf[]

* NSE のデータシート
+
https://www.netapp.com/us/media/ds-3213-en.pdf[]

* ONTAP 9 ドキュメンテーション・センター
+
http://docs.netapp.com[]

* NetApp and Federal Information Processing Standard （ FIPS ） 140-2 』を参照できます
+
https://www.netapp.com/company/trust-center/compliance/fips-140-2/[]

* Cisco および FIPS 140-2 への準拠
+
https://www.cisco.com/c/en/us/solutions/industries/government/global-government-certifications/fips-140.html[]

* NetApp Cryptographic Security Module の略
+
https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2648.pdf[]

* 中規模および大規模な医療機関向けのサイバーセキュリティの実践
+
https://www.phe.gov/Preparedness/planning/405d/Documents/tech-vol2-508.pdf[]

* Cisco and Cryptographic Module Validation Program （ CMVP ）
+
https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search?SearchMode=Basic&Vendor=cisco&CertificateStatus=Active&ValidationYear=0[]

* NetApp ストレージ暗号化、 NVMe 自己暗号化ドライブ、 NetApp Volume Encryption 、 NetApp Aggregate Encryption
+
https://www.netapp.com/pdf.html?item=/media/17073-ds-3898.pdf[]

* NetApp Volume Encryption および NetApp Aggregate Encryption の略
+
https://www.netapp.com/pdf.html?item=/media/17070-ds-3899.pdf[]

* NetApp Storage Encryption の略
+
https://www.netapp.com/pdf.html?item=/media/7563-ds-3213-en.pdf[]

* 電子医療記録システム用 FlexPod
+
https://www.netapp.com/pdf.html?item=/media/22199-tr-4881.pdf[]

* 現在のデータ：クラウド対応フラッシュテクノロジを使用した Epic EHR 環境でパフォーマンスを向上
+
https://www.netapp.com/media/10809-cloud-connected-flash-wp.pdf[]

* Epic EHR インフラ向け FlexPod データセンター
+
https://www.netapp.com/pdf.html?item=/media/17061-ds-3683.pdf[]

* Epic EHR 向け FlexPod データセンター導入ガイド
+
https://www.netapp.com/media/10658-tr-4693.pdf[]

* MEDITECH ソフトウェア対応 FlexPod データセンターインフラ
+
https://www.netapp.com/media/8552-flexpod-for-meditech-software.pdf[]

* FlexPod 規格は MEDITECH ソフトウェアにも対応しています
+
https://blog.netapp.com/the-flexpod-standard-extends-to-meditech-software/[]

* FlexPod for MEDITECH の指向性サイジングガイド
+
https://www.netapp.com/pdf.html?item=/media/12429-tr4774.pdf[]

* 医療用画像処理用の FlexPod
+
https://www.netapp.com/media/19793-tr-4865.pdf[]

* 医療業界の AI
+
https://www.netapp.com/us/media/na-369.pdf[]

* ヘルスケア向けの FlexPod で変革を促進
+
https://flexpod.com/solutions/verticals/healthcare/[]

* Cisco とネットアップが提供する FlexPod
+
https://flexpod.com/[]





== 謝辞

* ネットアップ、テクニカルマーケティングエンジニア、 Abhinav Singh 氏
* ネットアップ、解決策 Architect Healthcare （ Epic ）、 Brian O'Menahony 氏
* ネットアップ、 Pursuit Business Development Manager 、 Brian Pruitt 氏
* ネットアップシニアソリューションアーキテクト、 Arvind Ramakrinan 氏
* ネットアップ、 FlexPod グローバルフィールド CTO 、 Michael Hommer 氏




== バージョン履歴

|===
| バージョン | 日付 | ドキュメントのバージョン履歴 


| バージョン 1.0 以降 | 2021年4月 | 初版リリース 
|===