---
sidebar: sidebar 
permalink: healthcare/ehr-epic-performance_executive_summary.html 
keywords: epic, performance, storage, efficiency, all, flash, fas, platform, ehr 
summary: ネットアップの All Flash FAS プラットフォームのストレージ効率とパフォーマンスを示すために、 AFF A300 および AFF A700 システムで Epic EHR のパフォーマンスを測定する調査を実施しました。 
---
= エグゼクティブサマリー
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ネットアップの All Flash FAS プラットフォームのストレージ効率とパフォーマンスを示すために、 AFF A300 および AFF A700 システムで Epic EHR のパフォーマンスを測定する調査を実施しました。ONTAP 9.5 を実行している AFF A300 および ONTAP 9.4 を実行している AFF A700 ストレージコントローラで、 Epic EHR ワークロードを実行しているそれぞれについて、データスループット、ピーク IOPS 、平均レイテンシを測定しました。SPC-2 テストと同様に、インラインの Storage Efficiency 機能もすべて有効にしました。

AFF A300 クラスタで Epic Genio ワークロードジェネレータを実行しました。このクラスタには、 3.8TB SSD を合計 24 本、 AFF A700 クラスタには 3.8TB SSD を合計 48 本搭載しています。テストでは、このクラスタにさまざまな負荷をかけて、 CPU の利用率がピークになるようにし、負荷のポイントごとに、ストレージの IOPS とレイテンシに関する情報を収集しました。

ネットアップでは、ソフトウェアのアップグレードを 1 回行うたびにパフォーマンスが 40~50% 向上しました。パフォーマンスの強化によるイノベーションは、ワークロードやプロトコルによってさまざまです。

Epic のパフォーマンステストで、 AFF A300 クラスタの IOPS が 75 、 000 IOPS 未満で 1 ミリ秒未満になったことが実証され、最大パフォーマンスは 18 、 929 IOPS で 1 ミリ秒未満に達したことが実証されました。IOPS が 200 、 000 以下のすべての負荷のポイントで、ストレージの一貫したレイテンシを 1 ミリ秒以下に抑えることができました。さらに、 AFF A700 クラスタの IOPS が 75 、 000 IOPS 未満で 1 ミリ秒未満で最大パフォーマンスが 319,000 IOPS 未満であったことも、 Epic のパフォーマンステストで実証されました。IOPS が 320 、 000 以下のすべての負荷のポイントで、ストレージの一貫したレイテンシを 1 ミリ秒以下に抑えることができました。
