---
sidebar: sidebar 
permalink: healthcare/ehr-epic-performance_additional_information.html 
keywords: additional, information, flexpod, epic, performance, testing 
summary: このドキュメントに記載されている情報の詳細については、以下のドキュメントまたは Web サイトを参照してください。 
---
= 追加情報の参照先
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


このドキュメントに記載されている情報の詳細については、次のドキュメントまたは Web サイトを参照してください。



== FlexPod 設計ゾーン

* NetApp FlexPod の設計ゾーン
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html["https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html"^]

* AFF DC と FC ストレージ（ MDS スイッチ）では、 NetApp FlexPod 、 vSphere 6.5U1 、および Cisco UCS Manager を使用します
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html"^]

* Cisco UCS で Epic を使用した Cisco のベストプラクティス
+
https://www.cisco.com/c/dam/en_us/solutions/industries/healthcare/Epic_on_UCS_tech_brief_FNL.pdf["https://www.cisco.com/c/dam/en_us/solutions/industries/healthcare/Epic_on_UCS_tech_brief_FNL.pdf"^]





== ネットアップテクニカルレポート

* TR-4693 ：『 FlexPod Datacenter for Epic EHR Deployment Guide 』
+
https://www.netapp.com/us/media/tr-4693.pdf["https://www.netapp.com/us/media/tr-4693.pdf"^]

* TR-4707 ：『 FlexPod for Epic Directional Sizing Guide 』
+
https://www.netapp.com/us/media/tr-4707.pdf["https://www.netapp.com/us/media/tr-4707.pdf"^]

* https://fieldportal.netapp.com/content/192896["TR-3929 ：『 Reallocate Best Practices Guide 』"^]
+
https://www.netapp.com/us/media/tr-3929.pdf[]

* TR-3987 ：『 Snap Creator Framework Plug-in for Intersystems Cach é 』
+
https://www.netapp.com/us/media/tr-3987.pdf[]

* TR-3928 ：『 NetApp Best Practices for Epic 』
+
https://www.netapp.com/us/media/tr-3928.pdf["https://www.netapp.com/us/media/tr-3928.pdf"^]

* TR-4017 ：『 FC SAN Best Practices 』
+
https://www.netapp.com/us/media/tr-4017.pdf["https://www.netapp.com/us/media/tr-4017.pdf"^]

* TR-3446 ：『非同期 SnapMirror ベストプラクティスガイド』
+
https://www.netapp.com/us/media/tr-3446.pdf["https://www.netapp.com/us/media/tr-3446.pdf"^]





== ONTAP のドキュメント

* ネットアップの製品マニュアル
+
https://www.netapp.com/us/documentation/index.aspx["https://www.netapp.com/us/documentation/index.aspx"^]

* Virtual Storage Console （ VSC ） for vSphere のドキュメント
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048["https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048"^]

* ONTAP 9 ドキュメンテーション・センター
+
http://docs.netapp.com/ontap-9/index.jsp["http://docs.netapp.com/ontap-9/index.jsp"^]





== Cisco Nexus 、 MDS 、 Cisco UCS 、および Cisco UCS Manager の各ガイドを参照してください

* Cisco UCS サーバの概要
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html"^]

* Cisco UCS ブレードサーバの概要
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html"^]

* Cisco UCS B200 M5 データシート
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html"^]

* Cisco UCS Manager の概要
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-manager/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-manager/index.html"^]

* Cisco UCS Manager 3.2 （ 3a ）インフラストラクチャバンドル（ Cisco.com の権限が必要）
+
https://software.cisco.com/download/home/283612660/type/283655658/release/3.2%25283a%2529["https://software.cisco.com/download/home/283612660/type/283655658/release/3.2%25283a%2529"^]

* Cisco Nexus 9300 プラットフォームスイッチ
+
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html"^]

* Cisco MDS 9148S FC スイッチ
+
https://www.cisco.com/c/en/us/products/storage-networking/mds-9148s-16g-multilayer-fabric-switch/index.html["https://www.cisco.com/c/en/us/products/storage-networking/mds-9148s-16g-multilayer-fabric-switch/index.html"^]


