---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-deploy_volume_configuration.html 
keywords: volume, provisioning, snapshot, copy, volume, default, aggregate, reallocate, schedule 
summary: MEDITECH ホスト専用の MEDITECH ボリュームはシックプロビジョニングでもシンプロビジョニングでもかまいませんが、 Snapshot コピーを使用してアクセスできます。また、ボリュームレベルの再割り当てを使用してディスク上のデータレイアウトを最適化し、書き込みレイテンシとシーケンシャル読み取りアクセスを改善することもできます。 
---
= ボリューム構成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== ボリュームのプロビジョニング

MEDITECH ホスト専用の MEDITECH ボリュームはシックプロビジョニングでもシンプロビジョニングでもかまいません。



== ボリュームレベルのデフォルトの Snapshot コピー

Snapshot コピーはバックアップワークフローの一環として作成されます。各 Snapshot コピーを使用して、 MEDITECH LUN に格納されているデータに異なる時間でアクセスできます。MEDITECH 承認のバックアップ解決策は、これらの Snapshot コピーに基づいてシンプロビジョニングされた FlexClone ボリュームを作成し、 MEDITECH LUN のポイントインタイムコピーを提供します。MEDITECH 環境は、認定済みのバックアップソフトウェア解決策と統合されています。そのため、 MEDITECH の本番データベース LUN を構成する NetApp FlexVol ボリュームごとに、デフォルトの Snapshot コピースケジュールを無効にすることを推奨します。

* 重要： FlexClone ボリュームは親データボリュームのスペースを共有するため、バックアップサーバが作成する MEDITECH データ LUN と FlexClone ボリュームに十分なスペースをボリュームに確保しておくことが重要です。FlexClone ボリュームは、データボリュームが占めるスペースの増加は行いません。ただし、 MEDITECH LUN が短時間で大幅に削除された場合は、クローンボリュームが大きくなる可能性があります。



== アグリゲートあたりのボリューム数

Flash Pool キャッシュまたは NetApp Flash Cache キャッシュを使用する NetApp FAS システムについては、 MEDITECH プログラム、ディクショナリ、およびデータファイルの格納専用のボリュームをアグリゲートごとに 3 つ以上プロビジョニングすることを推奨します。

AFF システムについては、 MEDITECH のプログラム、ディクショナリ、データファイルを格納するボリュームをアグリゲートごとに 4 つ以上確保することを推奨します。



== ボリュームレベルの再割り当てスケジュール

特に MEDITECH 拡張プラットフォーム '6.x プラットフォーム 'C/S 5.x プラットフォームなどの書き込み負荷の高いワークロードで使用される場合 ' ストレージのデータ・レイアウトは時間の経過とともに最適化されません時間の経過とともに、シーケンシャルリードのレイテンシが高くなり、バックアップが完了するまでの時間が長くなる可能性があります。データレイアウトが適切でないか、断片化が書き込みレイテンシに影響する可能性もあります。ボリュームレベルの再割り当てを使用してディスク上のデータのレイアウトを最適化することで、書き込みレイテンシの低減とシーケンシャル読み取りアクセスの向上を実現できます。ストレージレイアウトが改善され、割り当てられた時間の 8 時間以内にバックアップが完了するようになりました。

|===
| ベストプラクティス 


 a| 
少なくとも、週単位のボリューム再割り当てスケジュールを実装して、割り当てられたメンテナンス時または本番用サイトのピーク時以外の時間帯に再割り当て処理を実行することを推奨します。


NOTE: ネットアップでは、コントローラごとに一度に 1 つのボリュームで再割り当てタスクを実行することを強く推奨します。

|===
業務用データベース・ストレージに適したボリューム再配置スケジュールの決定の詳細については、のセクション 3.12 を参照してください https://fieldportal.netapp.com/content/192896["ネットアップの TR-3929 ：『 Reallocate Best Practices Guide 』"^]。また、ビジー状態のサイトに対して週次再配置スケジュールを作成する方法についても説明します。

link:ehr-meditech-deploy_lun_configuration.html["次の例は、 LUN の構成を示して"]
