---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-deploy_design.html 
keywords: architecture, storage, layout, aggregates, database, disk, type, control, failover, hardware, aff 
summary: MEDITECH 向け FlexPod のアーキテクチャは、 MEDITECH 、 Cisco 、 NetApp のガイダンスや、 MEDITECH をご利用のお客様とあらゆる規模のお客様との連携に関するパートナー様の経験に基づいています。アーキテクチャは柔軟性に優れており、データセンターの戦略、組織の規模、システムの一元化、分散化、マルチテナント環境に応じて、 MEDITECH のベストプラクティスを適用できます。 
---
= 設計
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


MEDITECH 向け FlexPod のアーキテクチャは、 MEDITECH 、 Cisco 、 NetApp のガイダンスや、 MEDITECH をご利用のお客様とあらゆる規模のお客様との連携に関するパートナー様の経験に基づいています。アーキテクチャは柔軟性に優れており、データセンターの戦略、組織の規模、システムの一元化、分散化、マルチテナント環境に応じて、 MEDITECH のベストプラクティスを適用できます。

適切なストレージアーキテクチャは、合計 IOPS を使用した全体的なサイズによって決まります。パフォーマンスだけを重視するわけではなく、お客様の追加の要件に基づいて、より大きなノード数を使用する場合もあります。ネットアップストレージを使用する利点は、要件の変化に応じてクラスタを無停止で簡単にスケールアップできることです。また、機器の転用や機器の更新時に、ノードをクラスタから無停止で削除することもできます。

NetApp ONTAP ストレージアーキテクチャのメリットには、次のようなものがあります。

* * システムを停止することなく簡単にスケールアップ / スケールアウトできます。 * ONTAP のノンストップオペレーション機能を使用して、ディスクとノードをアップグレード、追加、または削除できます。ノードは 4 つから始めて 6 つに移動することも、大容量のコントローラに無停止でアップグレードすることもできます。
* * Storage Efficiency 。 * 重複排除、 NetApp FlexClone 、インライン圧縮、インラインコンパクション、シンレプリケーションにより、必要な総容量を削減 シンプロビジョニング、およびアグリゲートの重複排除：FlexClone 機能を使用すると、バックアップおよびテスト環境の更新に対応するクローンをほぼ瞬時に作成できます。これらのクローンは、変更が加えられるとストレージのみを消費します。
* * 災害復旧シャドウ・データベース・サーバ * 災害復旧シャドウ・データベース・サーバは ' ビジネス継続性戦略の一部です（ストレージの読み取り専用機能をサポートし ' ストレージの読み取り / 書き込みインスタンスとして構成される可能性があります）したがって、 3 つ目のストレージシステムの配置とサイジングは、通常、本番環境のデータベースストレージシステムと同じです。
* * データベースの整合性（多少考慮が必要）。 * NetApp SnapMirror バックアップコピーをビジネス継続性に関連して使用する場合は、を参照してください http://media.netapp.com/documents/tr-3446.pdf["TR-3446 ：『非同期 SnapMirror ベストプラクティスガイド』"^]。




== ストレージレイアウト



=== MEDITECH ホスト専用アグリゲート

MEDITECH の高パフォーマンスおよび高可用性要件を満たすための最初のステップは 'MEDITECH ホストの本番ワークロードを専用の高性能ストレージに分離するために 'MEDITECH 環境のストレージ・レイアウトを適切に設計することです

MEDITECH ホストのプログラムファイル、ディクショナリファイル、データファイルを格納するために、各ストレージコントローラに 1 つの専用アグリゲートをプロビジョニングする必要があります。他のワークロードが同じディスクを使用してパフォーマンスに影響しないように、それらのアグリゲートから他のストレージがプロビジョニングされることはありません。


NOTE: 他の MEDITECH サーバ用にプロビジョニングするストレージは、 MEDITECH ホストが使用する LUN 専用のアグリゲートに配置しないでください。他の MEDITECH サーバ用のストレージは別のアグリゲートに配置してください。その他の MEDITECH サーバのストレージ要件については、『 Hardware Configuration Proposal 』（新規導入の場合）および『 Hardware Evaluation Task 』（既存導入の場合）を参照してください。これらのドキュメントは、 MEDITECH システムインテグレータ、または MEDITECH テクニカルアカウントマネージャ（ TAM ）から MEDITECH を介して入手できます。ネットアップのソリューションエンジニアは、 NetApp MEDITECH Independent Software Vendor （ ISV ）チームと相談して、適切で包括的なネットアップストレージのサイジングを実施できます。



=== MEDITECH ホストのワークロードをすべてのストレージコントローラに均等に分散します

NetApp FAS システムと AFF システムは、 1 つ以上のハイアベイラビリティペアとして導入されます。MEDITECH の拡張機能と 6.x のワークロードを各ストレージコントローラに均等に分散し、各ストレージコントローラにコンピューティング、ネットワーク、キャッシングのリソースを適用することを推奨します。

MEDITECH のワークロードを各ストレージコントローラに均等に分散するには、次のガイドラインに従います。

* 各 MEDITECH ホストの IOPS がわかっている場合は、 MEDITECH の拡張ボリュームと 6.x のワークロードをすべてのストレージコントローラに均等に分散できるので、各コントローラが MEDITECH ホストから同じ数の IOPS を提供していることを確認できます。
* MEDITECH ホストごとに IOPS がわからない場合でも、 MEDITECH の拡張機能と 6.x のワークロードをすべてのストレージコントローラに均等に分散できます。MEDITECH ホストのアグリゲートの容量がすべてのストレージコントローラに均等に分散されていることを確認して、このタスクを完了します。これにより、 MEDITECH ホスト専用のすべてのデータアグリゲート間でディスク数が同じになります。
* 同様のディスクタイプと同一の RAID グループを使用して、両方のコントローラのストレージアグリゲートを作成し、ワークロードを均等に分散します。ストレージアグリゲートを作成する前に、 NetApp Certified Integrator にお問い合わせください。



NOTE: MEDITECH によると、 MEDITECH システムの 2 台のホストは他のホストよりも高い IOPS を生成します。この 2 つのホストの LUN は、別々のストレージコントローラに配置します。システムを導入する前に、 MEDITECH チームの支援を受けてこれら 2 つのホストを特定する必要があります。



== ストレージ配置



=== MEDITECH ホスト用のデータベース・ストレージ

MEDITECH ホストのデータベース・ストレージは、 NetApp FAS または AFF システムからブロック・デバイス（ LUN ）として提供されます。通常、 LUN は E ドライブとして Windows オペレーティングシステムにマウントされます。



=== その他のストレージ

MEDITECH のホストオペレーティングシステムとデータベースアプリケーションは、通常はストレージにかなりの IOPS を生成します。MEDITECH のホスト VM とその VMDK ファイルのストレージプロビジョニングは、必要に応じて、 MEDITECH のパフォーマンスしきい値を満たすために必要なストレージとは別のものとみなされます。

他の MEDITECH サーバ用にプロビジョニングされたストレージは、 MEDITECH ホストが使用する LUN 専用のアグリゲートに配置しないでください。他の MEDITECH サーバ用のストレージを別のアグリゲートに配置します。



== ストレージコントローラの構成



=== 高可用性

コントローラ障害の影響を軽減し、ストレージシステムの無停止アップグレードを可能にするには、ハイアベイラビリティモードでコントローラを搭載したストレージシステムを設定する必要があります。

ハイアベイラビリティコントローラペア構成では、ディスクシェルフを複数のパスでコントローラに接続する必要があります。この接続は、シングルパス障害から保護することでストレージの耐障害性を高め、コントローラフェイルオーバーが発生した場合のパフォーマンスの一貫性を向上させます。



=== ストレージコントローラのフェイルオーバー中のストレージパフォーマンス

ハイアベイラビリティペアのコントローラで構成されたストレージシステムでは、コントローラに障害が発生した場合でも、パートナーコントローラが、障害が発生したコントローラのストレージリソースとワークロードを引き継ぎます。コントローラに障害が発生した場合に満たす必要があるパフォーマンス要件をお客様に確認し、それに応じてシステムのサイズを決定することが重要です。



=== ハードウェアアシストテイクオーバー

ネットアップでは、両方のストレージコントローラでハードウェアアシストテイクオーバー機能を有効にすることを推奨します。

ハードウェアアシストテイクオーバーは、ストレージコントローラのフェイルオーバーにかかる時間を最小限に抑えるように設計されています。1 台のコントローラの Remote LAN Module またはサービスプロセッサモジュールが、ハートビートタイムアウトトリガーよりも早くコントローラ障害についてパートナーに通知できるため、フェイルオーバーにかかる時間が短縮されます。ハードウェアアシストテイクオーバー機能は、ハイアベイラビリティ構成ではストレージコントローラに対してデフォルトで有効になります。

ハードウェアアシストテイクオーバーの詳細については、を参照してください http://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 ドキュメンテーション・センター"^]。



=== ディスクタイプ

MEDITECH ワークロードに必要な読み取りレイテンシを抑えるために、 MEDITECH ホスト専用の AFF システムにアグリゲートを配置する場合は高性能の SSD を使用することを推奨します。



=== NetApp AFF

ネットアップは、高スループットが求められる MEDITECH ワークロードや、ランダムデータアクセスパターンや低レイテンシが求められる MEDITECH ワークロードに対応するハイパフォーマンス AFF アレイを提供しています。MEDITECH ワークロードに対応する AFF アレイは、 HDD ベースのシステムに比べてパフォーマンスに優れています。フラッシュテクノロジとエンタープライズデータ管理を組み合わせることで、パフォーマンス、可用性、ストレージ効率の 3 つの主要領域でメリットが得られます。



=== ネットアップのサポートツールおよびサービス

ネットアップでは、包括的なサポートツールとサービスを提供しています。NetApp AutoSupport ツールを有効にして、ハードウェア障害やシステム構成ミスが発生した場合にホームコールできるように NetApp AFF / FAS システムで設定する必要があります。ホームアラートをネットアップサポートチームに連絡することで、問題を迅速に解決できます。NetApp Active IQ は、ネットアップシステムの AutoSupport 情報に基づいた Web ベースのアプリケーションです。予測に基づいてプロアクティブに分析情報を提供することで、可用性、効率性、パフォーマンスの向上を支援します。
