---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-sizing_meditech_workload_overview.html 
keywords: meditech, workload, backup, cisco, ucs, reference, architecture, platforms 
summary: このセクションでは、 MEDITECH 環境に当てはまるコンピューティングワークロードとストレージワークロードの種類について説明します。 
---
= MEDITECH ワークロードの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このセクションでは、 MEDITECH 環境に当てはまるコンピューティングワークロードとストレージワークロードの種類について説明します。



== MEDITECH とバックアップのワークロード

MEDITECH 環境向けのネットアップストレージシステムをサイジングする場合は、 MEDITECH の本番用ワークロードとバックアップワークロードの両方を考慮する必要があります。

|===
| MEDITECH ホスト 


| MEDITECH ホストはデータベース・サーバですこのホストは MEDITECH ファイル・サーバ（拡張機能用 '6.x または C/S 5.x プラットフォーム用）または Magic マシン（ Magic プラットフォーム用）とも呼ばれます本ドキュメントでは、 MEDITECH ホストという用語を MEDITECH ファイルサーバと Magic マシンのことに使用しています。 
|===
以降のセクションでは、この 2 つのワークロードの I/O 特性とパフォーマンス要件について説明します。



== MEDITECH のワークロード

MEDITECH 環境では 'MEDITECH ソフトウェアを実行する複数のサーバが 'MEDITECH システムと呼ばれる統合システムとしてさまざまなタスクを実行しますMEDITECH システムの詳細については、 MEDITECH のドキュメントを参照してください。

* 本番環境の MEDITECH 環境については、該当する MEDITECH のドキュメントを参照して、ネットアップストレージシステムのサイジングに含める必要がある MEDITECH ホストの数とストレージ容量を確認してください。
* 新しい MEDITECH 環境については、ハードウェア構成の提案書を参照してください。既存の MEDITECH 環境については、ハードウェア評価タスクのドキュメントを参照してください。ハードウェア評価タスクは MEDITECH チケットに関連付けられています。お客様は、 MEDITECH からこれらのドキュメントのいずれかをリクエストできます。


MEDITECH システムを拡張して、ホストを追加することで容量とパフォーマンスを向上させることができます。各ホストには、そのデータベースファイルとアプリケーションファイル用のストレージ容量が必要です。各 MEDITECH ホストが使用できるストレージも、ホストが生成した I/O に対応している必要があります。MEDITECH 環境では ' 各ホストがそのホストのデータベースおよびアプリケーション・ストレージ要件をサポートするために 'LUN を使用できますMEDITECH カテゴリのタイプと導入するプラットフォームのタイプによって、各 MEDITECH ホストのワークロード特性とシステム全体のワークロード特性が決まります。



=== MEDITECH カテゴリ

MEDITECH では、導入規模とカテゴリ番号を 1 ～ 6 の範囲で関連付けています。カテゴリ 1 は MEDITECH の導入規模が最小で、カテゴリ 6 は最大です。各カテゴリに関連付けられている MEDITECH アプリケーション仕様には、次のようなメトリックが含まれます。

* 病院ベッドの数
* 1 年あたりの入院患者数
* 1 年あたりの外来患者数
* 緊急の客室訪問回数（年間）
* 1 年あたりの試験数
* 1 日あたりの入院処方
* 1 日あたりの外来処方


MEDITECH カテゴリの詳細については、 MEDITECH カテゴリのリファレンス・シートを参照してください。このシートは、 MEDITECH からお客様経由で入手するか、 MEDITECH システムのインストーラを使用して入手できます。



=== MEDITECH プラットフォーム

MEDITECH には 4 つのプラットフォームがあります。

* 拡張
* MEDITECH 6.x
* クライアント / サーバ 5.x （ C/S 5.x ）
* マジック


MEDITECH 拡張プラットフォーム '6.x プラットフォーム ' および C/S 5.x プラットフォームの場合 ' 各ホストの I/O 特性は 100% ランダムで ' 要求サイズは 4,000 ですMEDITECH Magic プラットフォームでは、各ホストの I/O 特性は 100% ランダムで、リクエストサイズは 8,000 または 16,000 です。MEDITECH によると、一般的な Magic Production Deployment の要求サイズは 8 、 000 または 1 、 000 です。

読み取りと書き込みの比率は、導入するプラットフォームによって異なります。MEDITECH では ' 読み取りと書き込みの平均の比率を予測してから ' それらを割合として表現していますMEDITECH では、特定の MEDITECH プラットフォーム上の MEDITECH ホストごとに必要な平均持続 IOPS 値も算出しています。次の表は、 MEDITECH が提供するプラットフォーム固有の I/O 特性をまとめたものです。

|===
| MEDITECH カテゴリ | MEDITECH プラットフォーム | 平均ランダムリード率 | 平均ランダムライト率 | MEDITECH ホストあたりの平均持続 IOPS 


| 1. | 拡張、 6.x | 20 | 80 | 750 


.4+| 2-6 | 拡張 | 20 | 80 | 750 


| 6.x | 20 | 80 | 750 


| C/S 5.x | 40 | 60 | 600 


| マジック | 90 | 10. | 400 
|===
MEDITECH システムの場合、各ホストの平均 IOPS レベルは上記の表に定義された IOPS 値と同じである必要があります。各プラットフォームに基づいて正しいストレージサイジングを決定するために、上記の表に記載されている IOPS 値が、に記載されているサイジング方法の一部として使用されます link:ehr-meditech-sizing_technical_specifications_for_small,_medium_and_large_architectures.html["小規模、中規模、大規模アーキテクチャの技術仕様"] セクション。

MEDITECH では、各ホストのランダムライトの平均レイテンシを 1 ミリ秒未満に抑える必要があります。ただし、バックアップジョブおよび再配置ジョブでは、書き込みレイテンシが一時的に 2 ミリ秒まで上昇することは許容されると考えられます。MEDITECH では ' カテゴリ 1 のホストで平均ランダム・リード・レイテンシーを 7ms 未満に ' カテゴリ 2 のホストでは 5ms 未満に抑える必要もありますこれらのレイテンシ要件は、 MEDITECH プラットフォームが使用されているかどうかに関係なく、すべてのホストに適用されます。

次の表に、 MEDITECH ワークロード用のネットアップストレージをサイジングする際に考慮する必要がある I/O 特性をまとめます。

|===
| パラメータ | MEDITECH カテゴリ | 拡張 | MEDITECH 6.x | C/S 5.x | マジック 


| リクエストのサイズ .2+| 1 ～ 6 | 4K | 4K | 4K | 8K または 16K 


| ランダム / シーケンシャル | 100% ランダム | 100% ランダム | 100% ランダム | 100% ランダム 


.2+| 平均持続 IOPS | 1. | 750 | 750 | 該当なし | 該当なし 


| 2-6 | 750 | 750 | 600 | 400 


| 読み取り / 書き込み比率 .2+| 1 ～ 6 | 読み取り 20% 、書き込み 80% | 読み取り 20% 、書き込み 80% | 読み取り 40% 、書き込み 60% | 読み取り 90% 、書き込み 10% 


| 書き込みレイテンシ | 1 ミリ秒未満 | 1 ミリ秒未満 | 1 ミリ秒未満 | 1 ミリ秒未満 


| ピーク時の書き込みレイテンシ | 1 ～ 6 | 2 ミリ秒未満 | 2 ミリ秒未満 | 2 ミリ秒未満 | 2 ミリ秒未満 


.2+| 読み取りレイテンシ | 1. | 7 ミリ秒未満 | 7 ミリ秒未満 | 該当なし | 該当なし 


| 2-6 | 5 ミリ秒未満 | 5 ミリ秒未満 | 5 ミリ秒未満 | 5 ミリ秒未満 
|===

NOTE: カテゴリ 3 ～ 6 の MEDITECH ホストの I/O 特性は ' カテゴリ 2 と同じですMEDITECH カテゴリ 2 ～ 6 の場合 ' 各カテゴリに導入されるホストの数は異なります

ネットアップストレージシステムは、前のセクションで説明したパフォーマンス要件を満たすようにサイジングする必要があります。MEDITECH の本番用ワークロードに加えて、ネットアップのストレージシステムは、バックアップ処理中にこれらの MEDITECH のパフォーマンスターゲットを保持できる必要があります。詳細については、次のセクションを参照してください。



== バックアップワークロードの概要

MEDITECH 認定バックアップ・ソフトウェアは 'MEDITECH システムの各 MEDITECH ホストで使用されている LUN をバックアップしますバックアップをアプリケーションと整合性のある状態にするには、バックアップソフトウェアが MEDITECH システムを休止し、ディスクへの I/O 要求を一時停止します。システムが休止状態になると、バックアップソフトウェアはネットアップストレージシステムにコマンドを発行して、 LUN を含むボリュームの NetApp Snapshot コピーを作成します。バックアップ・ソフトウェアはあとで MEDITECH システムの休止を解除し ' 本番 I/O 要求がデータベースに継続できるようにしますSnapshot コピーに基づいて、 NetApp FlexClone ボリュームが作成されます。このボリュームはバックアップソースによって使用され、 LUN をホストする親ボリュームで本番環境の I/O 要求が継続されます。

バックアップソフトウェアによって生成されるワークロードは、 FlexClone ボリューム内に存在する LUN のシーケンシャルリードから発生します。このワークロードは、 100% のシーケンシャルリードワークロードと定義されており、要求サイズは 64,000 です。MEDITECH の本番ワークロードについては、必要な IOPS と関連する読み取り / 書き込みレイテンシレベルを維持することがパフォーマンス基準となります。ただし、バックアップ・ワークロードでは、バックアップ処理中に生成されたデータの総スループット（ MBps ）に注意がシフトされます。MEDITECH LUN のバックアップは 8 時間以内に完了する必要がありますが、すべての MEDITECH LUN のバックアップは 6 時間以内に完了することを推奨します。バックアップを 6 時間以内に完了することを目標にすると、 MEDITECH のワークロードが計画外に増加した場合や、 NetApp ONTAP のバックグラウンド処理が増えた場合など、一定の期間にわたってデータが増加した場合にもその数を軽減できます。これらのいずれかのイベントによって、追加のバックアップ時間が発生する可能性があります。保存されているアプリケーション・データの量にかかわらず ' バックアップ・ソフトウェアは 'MEDITECH ホストごとに LUN 全体のブロック・レベルのフル・バックアップを実行します

このウィンドウ内でバックアップを完了するために必要なシーケンシャルリードのスループットを、次の要因に応じて計算します。

* 必要なバックアップ期間
* LUN の数
* バックアップする各 LUN のサイズ


たとえば、 50 ホストの MEDITECH 環境で、各ホストの LUN サイズが 200GB の場合、バックアップする LUN の合計容量は 10TB になります。

8 時間で 10TB のデータをバックアップするには、次のスループットが必要です。

* = （ 10 x 10^6 ） MB （ 8 x 3 、 600 ）
* = 347.2MBps


ただし、計画外のイベントを考慮して、控えめなバックアップ期間として 5.5 時間を選択し、推奨される 6 時間を超えるヘッドルームを確保します。

8 時間で 10TB のデータをバックアップするには、次のスループットが必要です。

* = （ 10 x 10^6 ） MB （ 5.5 x 3 、 600 ）
* = 500Mbps


500Mbps のスループットレートでは、バックアップは 5.5 時間以内に完了し、 8 時間のバックアップ要件内で快適に完了できます。

次の表に、ストレージシステムのサイズ設定時に使用するバックアップワークロードの I/O 特性をまとめます。

|===
| パラメータ | すべてのプラットフォーム 


| リクエストのサイズ | 64K 


| ランダム / シーケンシャル | 100% シーケンシャル 


| 読み取り / 書き込み比率 | 100% 読み取り 


| 平均スループット | MEDITECH ホストの数と各 LUN のサイズによって異なる：バックアップは 8 時間以内に完了する必要があります 


| 必要なバックアップ期間 | 8 時間 
|===


== MEDITECH 向け Cisco UCS リファレンスアーキテクチャ

MEDITECH on FlexPod のアーキテクチャは、 MEDITECH 、 Cisco 、 NetApp のガイダンスと、 MEDITECH をご利用のお客様とあらゆる規模のお客様との連携に関するパートナー様の経験に基づいています。このアーキテクチャは柔軟性が高く、お客様のデータセンター戦略に応じて、 MEDITECH のベストプラクティスを適用します。つまり、小規模でも大規模でも、一元化されたものでも、分散型でも、マルチテナント型でも同様です。

MEDITECH を導入する際、シスコは MEDITECH のベストプラクティスに直接適合する Cisco UCS リファレンスアーキテクチャを設計しました。Cisco UCS は、高性能、高可用性、信頼性、拡張性を備えた緊密に統合された解決策を提供し、医師の診療や病院のシステムに数千台のベッドを使用しています。
