---
sidebar: sidebar 
permalink: healthcare/ehr-epic-deploy_cisco_ucs_blade_server_and_switch_configuration.html 
keywords: cisco, ucs, blade, server, switch, configuration 
summary: Epic 対応 FlexPod ソフトウェアは、フォールトトレランスをあらゆるレベルで実現するように設計されています。システムに単一点障害がない。本ドキュメントは、 Epic 対応 FlexPod 環境の基本構成に関する概要を説明したものです。 
---
= Cisco UCS ブレードサーバとスイッチの構成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Epic 対応 FlexPod ソフトウェアは、フォールトトレランスをあらゆるレベルで実現するように設計されています。システムに単一点障害がない。最適なパフォーマンスを得るために、ホットスペアブレードサーバの使用をお勧めします。

本ドキュメントは、 Epic 対応 FlexPod 環境の基本構成に関する概要を説明したものです。このセクションでは、 FlexPod 構成の Cisco UCS コンピューティングプラットフォーム要素を準備するための手順の概要と例をいくつか示します。このガイダンスの前提条件として、 FlexPod 構成がラックに設置され、電源が投入されて、 FC ストレージを使用する FlexPod データセンターの手順に従ってケーブル接続されていることが必要です。



== Cisco Nexus スイッチの設定

耐障害性に優れた Cisco Nexus 9300 シリーズイーサネットスイッチペアが解決策用に導入されます。これらのスイッチは、の説明に従ってケーブル接続する必要があります link:ehr-epic-deploy_deployment_and_configuration_overview.html#cabling-diagram["「配線図」"] Cisco Nexus 構成では、イーサネットトラフィックフローが Epic アプリケーション向けに最適化されています。

. 初期セットアップとライセンスの完了後、次のコマンドを実行して両方のスイッチにグローバル設定パラメータを設定します。
+
....
spanning-tree port type network default
spanning-tree port type edge bpduguard default
spanning-tree port type edge bpdufilter default
port-channel load-balance src-dst l4port
ntp server <global-ntp-server-ip> use-vrf management
ntp master 3
ip route 0.0.0.0/0 <ib-mgmt-vlan-gateway>
copy run start
....
. グローバルコンフィギュレーションモードを使用して、各スイッチに解決策用の VLAN を作成します。
+
....
vlan <ib-mgmt-vlan-id>
name IB-MGMT-VLAN
vlan <native-vlan-id>
name Native-VLAN
vlan <vmotion-vlan-id>
name vMotion-VLAN
vlan <vm-traffic-vlan-id>
name VM-Traffic-VLAN
vlan <infra-nfs-vlan-id>
name Infra-NFS-VLAN
exit
copy run start
....
. に従って、トラブルシューティング用の NTP 配信インターフェイス、ポートチャネル、ポートチャネルパラメータ、およびポートの説明を作成します https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html["FlexPod データセンターと FC の Cisco Validated Design の 2 つの機能があります"^]。


link:ehr-epic-deploy_esxi_configuration_best_practices.html["次のセクションでは、 ESXi の構成のベストプラクティスを説明します"]
