---
sidebar: sidebar 
permalink: healthcare/ehr-epic-performance_conclusion.html 
keywords: flash, storage, epic, array, pools, adaptive, qos, performance 
summary: 2020 年までに、 Epic の利用者はすべてフラッシュストレージに移行する必要があります。NetApp ONTAP は、 Epic で高品質のオールフラッシュアレイとして初めて導入されたソリューションで、エンタープライズストレージアレイにランクインしています。GA バージョンの ONTAP を実行するネットアップのプラットフォームはすべて快適です。 
---
= まとめ
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


2020 年までに、 Epic の利用者はすべてフラッシュストレージに移行する必要があります。NetApp ONTAP は、 Epic で高品質のオールフラッシュアレイとして初めて導入されたソリューションで、エンタープライズストレージアレイにランクインしています。GA バージョンの ONTAP を実行するネットアップのプラットフォームはすべて快適です。

EPIC は、本番、レポート、 Clarity などの重要なワークロードを、プールと呼ばれるストレージの割り当てに物理的に分離する必要がある。ネットアップでは、ノードごとに 1 つのクラスタで複数のストレージプールを提供し、 Epic 解決策全体で単一のクラスタと単一の OS を提供しています。ONTAP では、 NAS と SAN のすべてのプロトコルがサポートされており、 SSD 、 HDD 、クラウド向けに異なるストレージ階層が混在しています。

ONTAP 9.3 でアダプティブ QoS が導入され、 ONTAP 9.4 の大幅な機能拡張が行われたことで、物理的な分離を必要とせずにソフトウェアを使用してストレージプールを作成できるようになりました。この機能は、アーキテクチャ開発を大幅に簡易化し、ノードやディスクを統合できるようにします。また、本番環境のような重要なワークロードでは、ノード間に分散することでパフォーマンスを向上させることができます。また、 Bully が原因のストレージパフォーマンスの問題も解消され、ワークロードのライフサイクルが安定したパフォーマンスが保証されます。
