---
sidebar: sidebar 
permalink: ent-db/fpd-oracle-rac-db.html 
keywords: flexpod, datacenter, oracle, rac, cisco, ucs, aff, mds, deploy 
summary: Cisco Validated Designには、お客様の導入を促進および改善するために設計、テスト、文書化されたシステムとソリューションが含まれます。 
---
= Cisco UCS および NetApp AFF A シリーズ上の FlexPod データセンターと Oracle RAC データベース
:allow-uri-read: 


Tushar Patel、Cisco Hardikkumar Vyas、Cisco

Cisco Validated Designには、お客様の導入を促進および改善するために設計、テスト、文書化されたシステムとソリューションが含まれます。これらの設計には、お客様のビジネスニーズに対応するために開発されたソリューションポートフォリオに、幅広いテクノロジと製品が組み込まれています。Ciscoとネットアップは提携してFlexPod を提供しています。は、さまざまなワークロードの基盤として機能し、お客様の要件に基づいて効率的なアーキテクチャ設計を実現します。FlexPod 解決策 は、Ciscoとネットアップのテクノロジを共有クラウドインフラとして導入するための検証済みのアプローチです。

FlexPod Datacenter with NetApp All Flash AFF システムは、Ciscoとネットアップの優れたテクノロジを組み合わせた、エンタープライズアプリケーション向けの強力な統合プラットフォームを構築した統合インフラプラットフォームです。CiscoとネットアップはOracleと緊密に連携し、今日のビジネスで必要とされる、きわめて要件の厳しいトランザクションデータベースや応答時間重視のデータベースをサポートしています。

このCisco Validated Design（CVD）では、可用性の高いOracle RACデータベース環境を導入するための、Cisco UCSとNetApp All Flash AFF Storageを使用したFlexPod データセンターアーキテクチャのリファレンスについて説明します。このドキュメントでは、関連するコンポーネントのハードウェアとソフトウェアの構成と、さまざまなテストの結果を示します。また、Cisco UCSコンピューティングサーバ、Ciscoファブリックインターコネクトスイッチ、Cisco MDSスイッチ、Cisco Nexusスイッチ、NetApp AFF ストレージ、Oracle RACデータベースを使用した実装とベストプラクティスのガイダンスも提供します。

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html["Cisco UCS および NetApp AFF A シリーズ上の FlexPod データセンターと Oracle RAC データベース"^]
