---
sidebar: sidebar 
permalink: ent-db/fpd-sap-sql.html 
keywords: flexpod, cisco, white, paper,sap, non-hana, sql 
summary: 現在のIT業界は、データセンターソリューションの劇的な変革を目の当たりにしています。 
---
= ホワイトペーパー『SAP Non-HANA with SQL』-『Design』
:allow-uri-read: 


[role="lead"]
現在のIT業界は、データセンターソリューションの劇的な変革を目の当たりにしています。近年、検証済みで設計されたデータセンターソリューションに大きな関心が寄せられています。重要な領域での仮想化テクノロジーの導入は、これらのソリューションの設計原則とアーキテクチャに大きな影響を与えました。これにより、ベアメタルシステム上で実行されている多くのアプリケーションを、新しい仮想化統合ソリューションに移行できるようになりました。FlexPod は、IT部門の急速に変化するニーズに対応するように設計された、事前検証済みで設計されたデータセンター解決策 の1つです。Ciscoとネットアップは提携してFlexPod を提供しています。このソリューションでは、データベース、エンタープライズリソースプランニング（ERP）、顧客関係管理（CRM）、Webアプリケーションなど、さまざまなエンタープライズワークロードの基盤として、業界最高クラスのコンピューティング、ネットワーク、ストレージコンポーネントを使用します。

近年、ITアプリケーション、特にデータベースの統合に大きな関心が寄せられています。過去数年間で最も広く採用され、導入されているデータベースプラットフォームは、Microsoft SQL Serverです。SQL Serverデータベースは、データベーススプロールの影響を受けることが多く、サーバの利用率の低さ、ライセンスの不正確さ、セキュリティ上の懸念、管理上の懸念、膨大な運用コストなど、ITの課題につながっています。そのため、SQL Serverデータベースは、堅牢性、柔軟性、耐障害性に優れたプラットフォーム上での統合に適しています。このドキュメントでは、SQL Serverデータベースを導入および統合するためのFlexPod リファレンスアーキテクチャについて説明します。

link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/sap-appservers-flexpod-with-sql.pdf["ホワイトペーパー『SAP Non-HANA with SQL』-『Design』"^]
