---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_new.html 
keywords: 'netapp, cisco, ontap, intersight, flexpod, what"s new, features, release notes, enhancements' 
summary: Cisco Intersight には、新機能、拡張機能、バグ修正を提供する新しいリリースが導入されています。 
---
= 新機能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


このセクションでは、 Cisco Intersight と NetApp ONTAP ストレージに利用できる新機能を紹介します。



== 2022 年 1 月

* NetApp Active IQ Unified Manager 9.10 以降のイベントベースのサイト間アラームが追加されました。



NOTE: 今後のリリースとの互換性を確保し、すべての機能を利用できるようにするために、 NetApp Active IQ Unified Manager をバージョン 9.10 にアップグレードすることを推奨します。

* Storage Virtual Machine に対して各プロトコルを明示的に有効（ true または false ）に設定します
* clusterHealthStatus 状態を正常にマッピングしました。 -suppressed を OK に設定します
* クラスタリストページで Health 列の名前が Cluster Status 列に変更されました
* クラスタが停止しているか到達不能である場合に、ストレージアレイ「 Unreachable 」を表示します
* クラスタの全般ページで Health 列の名前が Array Status 列に変更されました
* SVM に「 Volumes 」タブが追加され、 SVM のすべてのボリュームが表示されます
* ボリュームに Snapshot 容量セクションがあります
* ライセンスが正しく表示されるようになりました




== 2021年10月

* Cisco Intersight に含まれるネットアップストレージのタスクの最新リストを追加しました。を参照してください link:ci-qsg_use_cases.html["使用例 3 デザイナフリーフォームを使用したカスタムワークフロー"] NetApp ストレージ・タスクの一覧を表示します。
* クラスタリストページに Health 列が追加されました。
* 選択したクラスタの全般ページで詳細が表示されるようになりました。
* ナビゲーションペインから NTP サーバテーブルにアクセスできるようになりました。
* Storage Virtual Machine の General ページを含む新しい Sensors タブが追加されました。
* VLAN およびリンクアグリゲーショングループの概要が、 Port General ページで使用できるようになりました。
* ボリューム合計容量テーブルに追加された合計データ容量列。
* Average Volume Statistics テーブル、 Average LUN Statistics テーブル、 Average Aggregate Statistics テーブル、 Average Storage VM Statistics テーブル、および Average Node Statistics テーブルに追加されたレイテンシ、 IOPS 、およびスループットの列
+

NOTE: 上記のパフォーマンス指標は、 NetApp Active IQ Unified Manager 9.9 以降で監視されるストレージアレイでのみ使用できます。


