---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_new.html 
keywords: 'netapp, cisco, ontap, intersight, flexpod, what"s new, features, release notes, enhancements' 
summary: Cisco Intersight には、新機能、拡張機能、バグ修正を提供する新しいリリースが導入されています。 
---
= 新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


このセクションでは、 Cisco Intersight と NetApp ONTAP ストレージに利用できる新機能を紹介します。



== 2023年1月


NOTE: 最新リリースとの互換性を確保し、すべての機能を利用するには、NetApp Active IQ Unified Manager 9.12 GAへのアップグレードが必要です。このリリースに関連する既知の問題のリストについては、を参照してください <<既知の問題>>。

* 互換性チェックを実行するときに、相互接続性チェックでUCSMモードとIMMファームウェアモードを区別できるようになりました。
* ONTAP 9.7の場合、保護関係はサイト間に表示されません。この問題 はONTAP 9.8RC1で修正されました。




== 2022年8月


NOTE: 最新リリースとの互換性を確保し、すべての機能を利用するには、NetApp Active IQ Unified Manager 9.11 GAへのアップグレードが必要です。このリリースに関連する既知の問題のリストについては、を参照してください <<既知の問題>>。

* クラスタの使用可能容量の計算方法がSystem Managerに合わせて更新されました
* クラスタの全般ページが更新され、パフォーマンスデータが表示されるまでパフォーマンス指標の概要が非表示になりました
* クラスタの全般ページUI問題 が修正され、ページがハングする場合がある
* CIFS共有、CIFSサービス、qtree、およびSVM SnapMirrorポリシーがバックエンドインベントリに追加されました。
* Logical inventoryセクションのUIナビゲーションメニューに共有およびqtreeを追加しました
* 選択したStorage VMから共有をタブとして追加しました
* Storage VMでCIFSが有効になっている場合に、Storage VMのGeneralタブにCIFSサービス情報が追加されました
* ネットアップストレージシステムの構成の検証に使用するクラスタチェックページがベストプラクティスに準拠していることを確認できるようになりました




== 2022年7月

* Capacityウィジェットでクラスタデータ削減比率のビジュアルが向上しました
* [Network Interfaces]ページにFCインターフェイスタブを追加しました
* 汎用の「新しいストレージボリューム」タスクを使用して新しいボリュームを作成すると、ボリュームのスペースギャランティがnoneに設定され、Snapshotリザーブの割合が0%に設定されるようになりました
* Edit Snapshot PolicyタスクのCommentフィールドは省略可能になり、必須ではなくなりました
* UIインベントリとオーケストレーションの一貫性が向上
* Cluster Capacityのサイト間の容量情報がSystem Managerと同じになりました
* 操作性を向上させるために新しい管理インターフェイスを作成する際にすべてのパラメータを表示するチェックボックスをStorage Virtual Machineタスクの下に追加しました
* クライアント一致より下にプロトコルを移動しましたが、System Managerと同じ結果が得られました
* エクスポートポリシーの一般ページにアクセスプロトコルが表示されるようになりました
* igroupの削除は、条件付きでログに記録される
* 新しいストレージNASデータインタフェースと新しいストレージiSCSIデータインタフェースの下に、NASの「フェールオーバーポリシー」および「自動設定」パラメータを追加
* 新規ストレージNASスマートボリュームのロールバックタスクで、他のボリュームが関連付けられていない場合にエクスポートポリシーが削除されるようになりました
* Smart VolumeとSmart LUNタスクの機能強化




== 2022 年 4 月


NOTE: 今後のリリースとの互換性を確保し、すべての機能を利用できるように、 NetApp Active IQ Unified Manager をバージョン 9.10P1 にアップグレードすることを推奨します。

* Ethernet Port Detail ページにブロードキャストドメインを追加
* ユーザインターフェイス内のアグリゲートおよび SVM の「集約」を「階層」に変更しました
* 「クラスタステータス」を「アレイステータス」に変更
* MTU フィルタが、 < 、 > 、 = 、 <= 、 >= 文字に対応できるようになりました
* クラスタのインベントリにネットワークインターフェイスページが追加されました
* クラスタインベントリに AutoSupport を追加
* ノードに cdpd .enable オプションを追加
* CDP ネイバーのオブジェクトを追加しました
* Cisco Intersight にネットアップワークフローのストレージタスクが追加されました。を参照してください link:ci-qsg_use_cases.html["使用例 3 デザイナフリーフォームを使用したカスタムワークフロー"] NetApp ストレージ・タスクの一覧を表示します。




== 2022 年 1 月

* NetApp Active IQ Unified Manager 9.10 以降のイベントベースのサイト間アラームが追加されました。



NOTE: 今後のリリースとの互換性を確保し、すべての機能を利用できるようにするために、 NetApp Active IQ Unified Manager をバージョン 9.10 にアップグレードすることを推奨します。

* Storage Virtual Machine に対して各プロトコルを明示的に有効（ true または false ）に設定します
* clusterHealthStatus 状態を正常にマッピングしました。 -suppressed を OK に設定します
* クラスタリストページで Health 列の名前が Cluster Status 列に変更されました
* クラスタが停止しているか到達不能である場合に、ストレージアレイ「 Unreachable 」を表示します
* クラスタの全般ページで Health 列の名前が Array Status 列に変更されました
* SVM に「 Volumes 」タブが追加され、 SVM のすべてのボリュームが表示されます
* ボリュームに Snapshot 容量セクションがあります
* ライセンスが正しく表示されるようになりました




== 2021年10月

* Cisco Intersight に含まれるネットアップストレージのタスクの最新リストを追加しました。を参照してください link:ci-qsg_use_cases.html["使用例 3 デザイナフリーフォームを使用したカスタムワークフロー"] NetApp ストレージ・タスクの一覧を表示します。
* クラスタリストページに Health 列が追加されました。
* 選択したクラスタの全般ページで詳細が表示されるようになりました。
* ナビゲーションペインから NTP サーバテーブルにアクセスできるようになりました。
* Storage Virtual Machine の General ページを含む新しい Sensors タブが追加されました。
* VLAN およびリンクアグリゲーショングループの概要が、 Port General ページで使用できるようになりました。
* ボリューム合計容量テーブルに追加された合計データ容量列。
* Average Volume Statistics テーブル、 Average LUN Statistics テーブル、 Average Aggregate Statistics テーブル、 Average Storage VM Statistics テーブル、および Average Node Statistics テーブルに追加されたレイテンシ、 IOPS 、およびスループットの列
+

NOTE: 上記のパフォーマンス指標は、 NetApp Active IQ Unified Manager 9.9 以降で監視されるストレージアレイでのみ使用できます。





== 既知の問題

* AIQUM 9.11以前のバージョンを使用している場合は、ストレージリストページに表示される値とストレージ全般ページの容量バーグラフの値が一致しません。この問題 を解決するには、AIQUM 9.12以降にアップグレードして、表示される容量値が正確であることを確認します。
* AIQUM 9.11以前を使用している場合、[Integrated Systems]ページの[Interoperability（相互運用性）]タブで実行されたチェックでは、IMMとUCSMのCiscoコンポーネントを正確に区別できません。この問題 を解決するには、AIQUM 9.12にアップグレードして、すべてのコンポーネントが正しく識別されるようにします。
* データ収集プロセス中にサイト間ストレージのインベントリデータに影響がないようにするには、サポートされていないONTAP クラスタ（ONTAP 9.7P1より前のバージョン）をActive IQ Unified Manager （AIQUM）から削除する必要があります。
* 要求されているすべてのターゲットで、FlexPod 統合システム相互運用性クエリーを正常に完了するには、9.11以上のAIQUMバージョンが必要です。
* ONTAP クラスタがFQDNを使用してAIQ -UMに追加されている場合、ストレージインベントリのチェックページは表示されません。ユーザがIPアドレスを使用してAIQ -UMにONTAP クラスタを追加する必要があります。

