---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: NetApp ONTAP ストレージと Cisco Intersight の統合に関するハードウェア、ソフトウェア、ライセンスの要件を満たしていることを確認します。 
---
= 要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp ONTAPストレージとCisco Intersightを統合するためのハードウェア、ソフトウェア、ライセンスの要件を満たしていることを確認します。



== ハードウェアとソフトウェアの要件

解決策の実装に必要な最小限のハードウェアコンポーネントとソフトウェアコンポーネントを以下に示します。解決策の特定の実装で使用されるコンポーネントは、お客様の要件に応じて異なる場合があります。

|===
| コンポーネント | 要件の詳細 


| NetApp ONTAP | ONTAP 9.7P1 以降 


| NetApp Active IQ Unified Manager の略 | 最新バージョンのNetApp Active IQ Unified Managerが必要（現在は9.14RC1） 


| ネットアップストレージアレイ | ONTAP 9.7P1以降でサポートされるすべてのONTAP ASA、AFF、FASストレージアレイ 


| 仮想化ハイパーバイザー | vSphere 7.0以降 
|===

NOTE: を参照してください https://intersight.com/help/saas/supported_systems["Cisco Intersightでサポートされるシステム"^] Cisco UCS Compute Components と UCSM バージョンの最小要件については、を参照してください。



== Cisco Intersight のライセンス要件

Cisco Intersightは、物理ストレージ（NetAppストレージ）の管理、自動化、最適化を行うインフラサービスやクラウドオーケストレーションサービスなどのサービスを提供しています。これらのサービスを使用して、Cisco UCSサーバとCisco HyperFlexシステムを管理できます。インフラサービスとCloud Orchestratorサービスでは、複数の階層を含むサブスクリプションベースのライセンスモデルが使用されます。選択したサブスクリプション期間に必要なCisco UCSサーバボリューム階層を選択できます。

.ライセンスモデル
Cisco Intersightインフラサービスのライセンスモデルが簡易化され、次の2つのティアが提供されるようになりました。

* * Cisco Intersight Infrastructure Services Essentials *- Essentialsライセンスレベルは、グローバルヘルスモニタリング機能、インベントリ、Cisco TAC統合によるプロアクティブなサポート、多要素認証、SDKおよびAPIアクセスなどのサーバ管理を提供します。
* * Cisco Intersight Infrastructure Services Advantage *- Advantageライセンスレベルでは、高度なサーバ管理と拡張された可視性、エコシステムの統合、シスコおよびサードパーティ製ハードウェアとソフトウェアの自動化、マルチドメインソリューションを提供します。


さまざまなライセンスレベルでサポートされる機能の詳細については、を参照してください https://intersight.com/help/saas/getting_started/licensing_requirements/lic_infra#licensing_model["Infrastructure Servicesライセンス"^]。
